### ISSUE TITLE
Split the dependencies

### ISSUE THREAD

**Issue by raphaelauv** [astronomer/astronomer-providers#101]
**Is your feature request related to a problem? Please describe.**
I would like to use only a part of this provider, in my case I only need the CNCF ( so I do not want all the aws , gcp .. depedencies )

**Describe the solution you'd like**
if I could do a pip install : 
```requirements
astronomer-providers[cncf]==1.0.0
```
**Describe alternatives you've considered**
Copy paste the CNCF folder of this repo inside my private dags repo

**Additional context**
I guess having all this great operators and hooks out of the official Airlfow project is on purpose, so I guess there is no plan to merge theses operators and hooks in the existing airflow providers ?

Thanks for all your work and open sourcing this great code :+1:

**Comment by kaxil** [comment]
Thanks @raphaelauv for creating the feature request, we are definitely planning to split the dependencies soon and allow installing dependencies using extras like `astronomer-providers[cncf.kubernetes]==1.0.0`.

**Comment by kaxil** [comment]
FYI: `1.1.0a2` alpha version is available for testing where you can run: `pip install astronomer-providers[cncf.kubernetes]==1.1.0a2` to just install Kubernetes provider.

Changelog: https://astronomer-providers.readthedocs.io/en/latest/changelog.html#a2-2022-03-19

We will release 1.1.0 - stable version on Monday/Tuesday.
