### ISSUE TITLE
Test aws_nuke dag with multiple worker on celery executor

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astronomer-providers#1045]
**Is your feature request related to a problem? Please describe.**
We have observed failures for the aws_nuke command, we suspect it might be because of the execution of credentials-related changes in one operator and the `aws_nuke` command on a different operator. Since the celery executor only has a single worker it's working but it might fail if we have more workers. So the credentials-related operation executes in one worker node and the aws_nuke executes in a different worker. 

ref: 
https://github.com/astronomer/astronomer-providers/blob/0f8635742f9171427ea482945fddcbdc1372a604/astronomer/providers/amazon/aws/example_dags/example_aws_nuke.py

**Describe the solution you'd like**
We want to test this theory.

**Comment by vatsrahul1001** [comment]
Already been tested and verified. Closing this
