### ISSUE TITLE
Replace "Query" with "Job" for EmrContainerOperatorAsync

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1105]
**Is your feature request related to a problem? Please describe.**
As discussed in https://github.com/astronomer/astronomer-providers/pull/1094#discussion_r1193859049

**Describe the solution you'd like**
Replace "Query" with "Job" for EmrContainerOperatorAsync

**Describe alternatives you've considered**

**Additional context**

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
