### ISSUE TITLE
Optimize deploy process

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1125]
**Is your feature request related to a problem? Please describe.**
Currently, we build the same image for deploying to both environments, which wastes resources.

**Describe the solution you'd like**
1. split up the deploy script
2. build the image one time and deploy to 2 environemnts

**Describe alternatives you've considered**

**Additional context**

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
