### ISSUE TITLE
Delete stale VPCs, subnets, route tables created from EMR DAG

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1131]
Currently, the `emr_eks_pi_job` DAG fails intermittently due to leftover VPCs created from earlier runs.
We need to identify a reliable automation (most probably in the same example DAG) to delete these while being extremely careful to not delete the 2 Databricks-related VPCs present in the account.

**Comment by phanikumv** [comment]
we can identify the VPC with the string **emr_eks_ctl**

**Comment by pankajkoti** [comment]
okay, will check this sometime soon.
