### ISSUE TITLE
check_fn not being used correctly in S3KeySensorAsync

### ISSUE THREAD

**Issue by sunank200** [astronomer/astronomer-providers#1166]
**Describe the bug**
When user passes `check_fn` which is a function that receives the list of the S3 objects, and returns a boolean. Currently the `check_fn` is not being used in the code at all: https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/amazon/aws/triggers/s3.py#L70-L76

**Expected behavior**

When user passes `check_fn`, it should use this python callable in sensor.
```
        if self.check_fn is not None:
            return self.check_fn(files)
```

**Comment by pankajastro** [comment]
unfortunately, the trigger can't serialise callable so we can't handle it in the trigger but if we want to implement it we can do it in `execute_complete` and then again defer

**Comment by pankajastro** [comment]
I have PR here https://github.com/astronomer/astronomer-providers/pull/1171 here PTAL if you feel positive then I'll add test etc
