### ISSUE TITLE
Implement Async for EMR Operators and Sensors

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#120]
Please look at docs to see if there are other operators we should make Async (Principle - Only create Async operators for the “sync-version” of operators that do some level of polling; take more than a few seconds to complete) for the EMR

Implement async versions for the following operators (Aligned on descending order of priority)
- [x] [`EmrCreateJobFlowOperator`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/operators/emr/index.html#airflow.providers.amazon.aws.operators.emr.EmrCreateJobFlowOperator)
- [x] [`EmrAddStepsOperator`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/operators/emr/index.html#airflow.providers.amazon.aws.operators.emr.EmrAddStepsOperator)
---
- [x] [`EmrContainerOperator`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/operators/emr/index.html#airflow.providers.amazon.aws.operators.emr.EmrContainerOperator)
- [x] [`EmrModifyClusterOperator`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/operators/emr/index.html#airflow.providers.amazon.aws.operators.emr.EmrModifyClusterOperator)
- [x] [`EmrTerminateJobFlowOperator`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/operators/emr/index.html#airflow.providers.amazon.aws.operators.emr.EmrTerminateJobFlowOperator)
- [x] [`EmrContainerSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/emr.html#amazon-emr-container-sensor)  -> @bharanidharan14 
- [x] [`EmrJobFlowSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/emr.html#amazon-emr-job-flow-sensor) -> @bharanidharan14
- [x] [`EmrStepSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/emr.html#amazon-emr-step-sensor) -> @pankajastro 

**Acceptance Criteria**:
- [x] Unit Tests coverage in the PR (90% Code Coverage -- We will need to add CodeCov separately to measure code cov) with all of them passing 
- [x] Example DAG using the async Operator that can be used to run Integration tests that are parametrized via Environment variables. Example - https://github.com/apache/airflow/blob/8a03a505e1df0f9de276038c5509135ac569a667/airflow/providers/google/cloud/example_dags/example_bigquery_to_gcs.py#L33-L35
- [x] Add proper docstrings for each of the methods and functions including Example DAG on how it should be used (populate 
- [x] Exception Handling in case of errors 
- [ ] Improve the OSS Docs to make sure it covers the following:
   - [ ] Has an example DAG for the sync version
   - [ ] How to add a connection via Environment Variable & explain each of the fields. Example - https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html
   - [ ] How to use Guide for the Operator - example: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html

**Comment by sunank200** [comment]
Both [EmrCreateJobFlowOperator](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/emr.py#L265) and  [EmrAddStepsOperator](https://github.com/apache/airflow/blob/main/airflow/providers/amazon/aws/operators/emr.py#L41) does not require the async implementation as an Operator.

If you look at the boto3 documentation for [run_job_flow](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.run_job_flow), it instantaneously returns the response with `JobFlowId` and `ClusterArn`. `EmrCreateJobFlowOperator` just takes the `job_flow_overrides` as an argument and creates an EMR JobFlow using  `job_flow_overrides` and it is not a blocking call (it returns the `JobFlowId`  instantaneously) The sync implementation of the operator does not care about the status of the EMR JobFlow and it's not tracking it. It just instantiates the creation of EMR Job but does not track the status of it.

Similarly in the `EmrAddStepsOperator`, it just adds the adds steps to an existing EMR job_flow and returns the step-ids using boto3 [add_job_flow_steps](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/emr.html#EMR.Client.add_job_flow_steps) but this operators does not track the status of the steps. So it does not require async implementation.

@kaxil @phanikumv

**Comment by phanikumv** [comment]
Yes I agree, I think only the below sensors will take a while to run and will need async implementation

- EmrContainerSensor
- EmrJobFlowSensor
- EmrStepSensor

**Comment by kaxil** [comment]
Based on https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/operators/emr.html -- agreed

**Comment by kaxil** [comment]
Is this completed, I don't see a PR for the following


- EmrContainerSensor
- EmrJobFlowSensor
- EmrStepSensor

**Comment by sunank200** [comment]
I am working on `SparkSqlOperator` as Phani had mentioned it has a higher priority.

**Comment by phanikumv** [comment]
Thats correct @kaxil , I requested Ankit and Bharani to switch over to implementing native Spark operators as part of #119 .

**Comment by pankajastro** [comment]
I have started working `EmrStepSensor`

**Comment by pankajastro** [comment]
PR opened `EmrStepSensor` https://github.com/astronomer/astronomer-providers/pull/184
