### ISSUE TITLE
[Releasing process] automatically create corresponding git tag after merging releasing branches

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1201]
**Is your feature request related to a problem? Please describe.**
Automate [this step](https://github.com/astronomer/astronomer-providers/blob/main/RELEASING.rst#tag-and-push-the-commit)

**Describe the solution you'd like**
Parse the merged pull request with branch name "release-a-b-c" and create git tag `a.b.c`

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajkoti** [comment]
Perhaps we could also check if we could automate the dev version bump post the release.

**Comment by Lee-W** [comment]
Yep, that shouldn't be too difficult and should be included in this change as well. Thanks for your suggestion!

**Comment by Lee-W** [comment]
Another thing I'm thinking of (not related to this issue) is whether we could somehow tag a PR as included in the changelog before merging so that we don't need to check all the commits and simply parse the commits with that pattern

**Comment by pankajkoti** [comment]
yes, I think we can refer to Airflow OSS on how they achieve building the ChangeLog for RCs. I believe they also add a label `changelog:skip` to PRs that they want to be skipped in ChangeLog. I think these ideas can be separate issues and separate PRs that will allow us to have incremental improvements :)
