### ISSUE TITLE
check_fn For S3KeySensorAsync Is Not Compatible With check_fn Of Its Super Class S3KeySensor

### ISSUE THREAD

**Issue by infohash** [astronomer/astronomer-providers#1213]
## Describe the bug
If you have specified `check_fn` for `S3KeySensorAsync`, its super class `S3KeySensor` will also call that `check_fn` like this:

https://github.com/astronomer/astronomer-providers/blob/96f75535dcc3749dade524d73de060ff17f11ea9/astronomer/providers/amazon/aws/sensors/s3.py#L88-L94

`self.poke` calls the method `poke` of super class `S3KeySensor`: https://github.com/apache/airflow/blob/62a534dbc7fa8ddb4c249ade85c558b64d1630dd/airflow/providers/amazon/aws/sensors/s3.py#L132-L136

```python
def poke(self, context: Context):
    if isinstance(self.bucket_key, str):
        return self._check_key(self.bucket_key)
    else:
        return all(self._check_key(key) for key in self.bucket_key)
```

This `poke` calls `_check_key` method of the super class `S3KeySensor`. The problem occurs inside this `_check_key` method if you have given `check_fn`: https://github.com/apache/airflow/blob/62a534dbc7fa8ddb4c249ade85c558b64d1630dd/airflow/providers/amazon/aws/sensors/s3.py#L127-L128

```python
...
    ...
        if self.check_fn is not None:
            return self.check_fn(files)
    ....
....
```

The example value of `files` it gives is `[{'Size': 100}, {'Size': 200}, {'Size': 300}]`. They have mentioned this in the docstring: https://github.com/apache/airflow/blob/62a534dbc7fa8ddb4c249ade85c558b64d1630dd/airflow/providers/amazon/aws/sensors/s3.py#L105C9-L111C12

```python
        """
        Set variable `files` which contains a list of dict which contains only the size
        If needed we might want to add other attributes later
        Format: [{
            'Size': int
        }]
        """
```

But the `S3KeyTrigger.run` method returns complete metadata:
https://github.com/astronomer/astronomer-providers/blob/96f75535dcc3749dade524d73de060ff17f11ea9/astronomer/providers/amazon/aws/triggers/s3.py#L79-L83

The example value of `s3_objects` here is:

```python
[
    {
        'Key': 'test.csv',
        'LastModified': DateTime(2023, 6, 25, 10, 10, 10, 855000, tzinfo=Timezone('UTC')),
        'ETag': '"333e09..."',
        'Size': 300,
        'StorageClass': 'STANDARD',
        'Owner': {
            'DisplayName': 'S3',
            'ID': '02d61...'
        }
    }
]
```

If you are writing `check_fn` based on this format, it will throw `KeyError` for missing keys in the dictionary whenever `S3KeySensor._check_key` will pass the value to your check_fn. `S3KeySensor.poke` always runs before `S3KeySensorAsync._defer` is called:

https://github.com/astronomer/astronomer-providers/blob/96f75535dcc3749dade524d73de060ff17f11ea9/astronomer/providers/amazon/aws/sensors/s3.py#L95-L96

This change was made recently in #1037 : https://github.com/astronomer/astronomer-providers/commit/1bc969a3f00a6c140c04b7a45bb7d78b8a3bd0e9 to implement **"poke before defer"** functionality.

## Solution
I think it is better to fix the output in upstream as the `Size` attribute of the bucket_key is not enough to validate the files. A user will likely expect name of the file to validate if the proper naming convention was followed which is how I encountered the `KeyError`. If we upstream it, we may have to upstream `use_regex` functionality as well otherwise `S3KeySensor` (with `wildcard_match` to `False`)  will disagree with `S3KeySensorAsync` (with `use_regex` to `True`).

## Workaround

Put this condition in your `check_fn` to disregard the value provided by `S3KeySensor._check_key`:

```python
    if values:
        _value, *args = values
        if not _value.get('Key'):
            return False
```

It checks if the first item in the list has the key name `Key`. If it does not, return `False` to defer it. Now follow up calls to your `check_fn` will have the value provided by `S3KeyTrigger.run` method.

**Comment by pankajastro** [comment]
At the moment, I think restricting the way we call chec_fn in the repo is the best option but if you feel we should add more attributes other than size then we need to make some changes in the Airflow repo and request you to create a separate feature request of it
