### ISSUE TITLE
Example DAG for Livy and Hive fails for multiple workers

### ISSUE THREAD

**Issue by sunank200** [astronomer/astronomer-providers#1221]
**Describe the bug**
The example DAG  for Livy and Hive adds the inbound rule for worker IP in security group which doesn't work for multiple workers.

More details on: https://astronomer.slack.com/archives/C037VQ1HCHZ/p1687948228459279

**Expected behavior**
DAG should run fine

**Comment by vatsrahul1001** [comment]
We do have these DAG running on multiple worker env now and its works well, if IP of workers are added its fine. Closing this
