### ISSUE TITLE
`snowflake` not included in the `extras_require` of `amazon` extra

### ISSUE THREAD

**Issue by ReadytoRocc** [astronomer/astronomer-providers#1259]
**Describe the bug**
The `RedshiftDataOperatorAsync` utilizes the `RedshiftDataHook`, which has a [dependency](https://github.com/astronomer/astronomer-providers/blob/1.17.1/astronomer/providers/amazon/aws/hooks/redshift_data.py#L12) on the `snowflake` python package. This is [not included](https://github.com/astronomer/astronomer-providers/blob/1.17.1/setup.cfg#L46-L48) in the `extras_require` of the `amazon` extra. This results in an import failure.

**To Reproduce**
- Install `astronomer-providers==1.17.1`
- Include the `amazon` extra.
- Import `RedshiftDataOperatorAsync`:
```
>>> from astronomer.providers.amazon.aws.operators.redshift_data import RedshiftDataOperatorAsync
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/astronomer/providers/amazon/aws/operators/redshift_data.py", line 6, in <module>
    from astronomer.providers.amazon.aws.hooks.redshift_data import RedshiftDataHook
  File "/usr/local/lib/python3.10/site-packages/astronomer/providers/amazon/aws/hooks/redshift_data.py", line 12, in <module>
    from snowflake.connector.util_text import split_statements
ModuleNotFoundError: No module named 'snowflake'
>>> 
```

**Comment by pankajkoti** [comment]
Instead of adding the extra, I worked on removing the snowflake dependency as suggested in Slack thread https://astronomer.slack.com/archives/C0387PMM2E7/p1690293653544339?thread_ts=1690244271.090079&cid=C0387PMM2E7 

Have created a PR for the same #1260
