### ISSUE TITLE
Test astronomer-providers on all supported Python versions

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1310]
Now that the runtime image supports multiple Python versions, modify our
setup and scripts to test the providers with all supported versions

**Comment by phanikumv** [comment]
This is completed I believe @pankajkoti ?

**Comment by pankajkoti** [comment]
Not yet @phanikumv. Our production hosted deployment only tests for Python 3.9 images https://github.com/astronomer/astronomer-providers/blob/main/.circleci/integration-tests/Dockerfile.astro_cloud#L2

The idea here was to discuss to see if we need deployments for each of the Python versions and if yes, modify our scripts to deploy on all Python version deployments. This would also mean we would need secrets configured for each of the deployments.

cc: @vatsrahul1001

**Comment by vatsrahul1001** [comment]
We do test now on multiple python env in our regression. closing this
