### ISSUE TITLE
Bring back hive support for Python 3.11

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#1312]
check if we can bring back hive support for Python 3.11 once PR https://github.com/apache/airflow/pull/32607 is released

**Comment by pankajkoti** [comment]
Do we need to wait for it to be released or can we pin a min version for the dependency in our list?

**Comment by pankajastro** [comment]
> Do we need to wait for it to be released or can we pin a min version for the dependency in our list?

OSS PR changes
```
- sasl>=0.3.1; python_version>="3.9"
+ pyhive[hive_pure_sasl]>=0.7.0
```
I'm wondering if the installation will still try to install the airflow hive provider old one which has sasl>=0.3.1 as a dependency and it causes a problem?

**Comment by pankajastro** [comment]
If I remember correctly `sasl` was causing issue and pip would still try to install it but we can try
