### ISSUE TITLE
HttpAsyncHook: cannot do an await response.text() or response.json() after run: "Connection closed"

### ISSUE THREAD

**Issue by andresferrari** [astronomer/astronomer-providers#1321]
**Describe the bug**
After the change in version `1.15.2` of `astronomer-providers`, it seems the `HttpAsyncHook` closes the connection after returning from `run(...)`. This means the body of the `ClientResponse` object can no longer be read, since it will raise a "Connection closed" error. Immediately before this fix, i.e. in `1.15.1`, one could do a `response.text()` or `response.json()`.

**To Reproduce**
1. Create an `HttpAsyncHook` with a "GET" method: `hook = HttpAsyncHook(method="GET", ...)`
2. Do an await on its `run` method: `response = await hook.run(...)`
3. Try to read the body of the response, also awaiting: `payload = await response.json()`
4. Error: `aiohttp.client_exceptions.ClientConnectionError: Connection closed`

**Expected behavior**
The calling code should be able to read the response body.

**Additional context**
I'm running this code inside an Airflow Trigger.

**Comment by andresferrari** [comment]
Additional information: I believe the commit that changed the behavior is in [this PR](https://github.com/astronomer/astronomer-providers/pull/927)

**Comment by Lee-W** [comment]
Hi @andresferrari , could you please provide the code that led to this failure? I'm not able to reproduce the same behavior.

I changed the code in https://github.com/astronomer/astronomer-providers/blob/1.17.3/astronomer/providers/http/triggers/http.py#L65-L76 as the following to simulate the situation you mentioned.

```python
        while True:
            try:
                response = await hook.run(
                    endpoint=self.endpoint,
                    data=self.data,
                    headers=self.headers,
                    extra_options=self.extra_options,
                )
                break
            except AirflowException as exc:
                if str(exc).startswith("404"):
                    await asyncio.sleep(self.poke_interval)

        print(response)
        payload = await response.json()
        print(payload)
        yield TriggerEvent(True)
```

Also commented out the code [here](https://github.com/astronomer/astronomer-providers/blob/1.17.3/astronomer/providers/http/sensors/http.py#L104-L107) so that we can be sure that we're running in the triggerer.

**Comment by Lee-W** [comment]
The DAG I'm using to test this is https://github.com/astronomer/astronomer-providers/blob/1.17.3/astronomer/providers/http/example_dags/example_http.py and set the HTTP hook host to `https://www.google.com/`

**Comment by Lee-W** [comment]
Or is there anything I misunderstood? Thanks!

**Comment by Lee-W** [comment]
@andresferrari Thanks for your prompt response. Let me check whether I can reproduce and see how I can fix it. Thanks!

**Comment by Lee-W** [comment]
I tried to add a `keep_response` argument in `HttpHookAsync` in this https://github.com/astronomer/astronomer-providers/pull/1330 for address this
