### ISSUE TITLE
KPO log reasons for not starting pod

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/astronomer-providers#1343]
**Is your feature request related to a problem? Please describe.**
When a KPO fails to start, it [logs](https://github.com/astronomer/astronomer-providers/blob/1.18.0/astronomer/providers/cncf/kubernetes/triggers/wait_container.py#L95) a generic message.  Especially when using a remote KPO, there is often a division of responsibility between maintaining the Kubernetes environment and running Airflow. A clear message would help with routing troubleshooting.

**Describe the solution you'd like**
The clear next troubleshooting step is to get all the kubernetes events on the pod, such as through a `kubectl describe pod`. It would be best if KPO simply did this automatically on timeout and logged these messages.

**Describe alternatives you've considered**
Status quo isn't disastrous, but this would be better.

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
