### ISSUE TITLE
Add secret for readthedoc webhook

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#1372]
docs: https://blog.readthedocs.com/security-update-on-incoming-webhooks/

Internal discussion: https://astronomer.slack.com/archives/C01UJJEN0P3/p1700047478577269

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this

**Comment by sunank200** [comment]
Waiting for permission [here](https://astronomer.slack.com/archives/C01UJJEN0P3/p1706185396803009?thread_ts=1700047478.577269&cid=C01UJJEN0P3)
