### ISSUE TITLE
EMR EKS DAG stabilisation for astronomer-providers

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1405]
Take care of cleaning up following resources:

- [ ] VPC created by the DAG
- [ ] OIDC created by the DAG

**Comment by phanikumv** [comment]
just see whether it is worth the time because we are planning to deprecate stuff soon.

**Comment by pankajkoti** [comment]
Even if we deprecate, wouldn't we keep running the integration tests? That would help us test the RCs right?

**Comment by phanikumv** [comment]
IMO , since we already have integration tests dashboard from Amazon on OSS, once we point our provider to use OSS one, we should remove integration tests as well - as we no longer maintain our version of providers.

**Comment by pankajkoti** [comment]
yes, that would be nice, we would save cost on spinning up AWS resources in that case

**Comment by vatsrahul1001** [comment]
OIDC deletion logic fixed in [PR](https://github.com/astronomer/astronomer-providers/pull/1408)

**Comment by vatsrahul1001** [comment]
as per discussion with @phanikumv I have raised request to increase VPC limit to 15

![Image](https://github.com/astronomer/astronomer-providers/assets/43964496/bcf32d6d-6ab1-4244-b670-f73207051933)

**Comment by pankajkoti** [comment]
@vatsrahul1001 do you think we can close this issue?

**Comment by vatsrahul1001** [comment]
@pankajkoti no I still see some failures due to this

**Comment by phanikumv** [comment]
Closing as the provider is being deprecated
