### ISSUE TITLE
Deprecate amazon async provider

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1410]
**Is your feature request related to a problem? Please describe.**

 as most of the functionality has been contributed back to OSS airflow, we're going to leverage the code there and deprecate this project

**Describe the solution you'd like**

1. Contribute the delta to the OSS provider
2. Point the astronomer provider to the OSS provider
3. Do the release and wait for a month or so before we remove the astronomer provider in a major release

**Describe alternatives you've considered**

**Additional context**

-----

## Current Progress
* Number of operator changes on OSS airflow needed: 10 (finished: 7)
* Number of operators to deprecate: 18 (finished: 9)

1. [x] `EmrContainerSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1390
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `EmrStepSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1390
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `EmrJobFlowSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1406
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**:
1. [x] `RedshiftClusterSensorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36550
    * **Minimum Provider Version**: 8.17.0
1. [x] `BatchSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1391
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `S3KeySensorAsync`
    * **Note**: different, miss `use_regex`
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36578
    * **Minimum Provider Version**: 8.17.0
1. [x] `S3KeySizeSensorAsync`
    * **Note**: already deprecated
    * **Action**: -
    * **Deprecation PR**: -
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `S3KeysUnchangedSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1398
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36363
    * **Minimum Provider Version**: 8.15.0
1. [x] `S3PrefixSensorAsync`
    * **Note**: already deprecated
    * **Action**: -
    * **Deprecation PR**: -
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `EmrContainerOperatorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1402
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36417
    * **Minimum Provider Version**: 8.15.0
1. [x] `RedshiftDeleteClusterOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1399
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36416
    * **Minimum Provider Version**: 8.16.0
1. [x] `RedshiftResumeClusterOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1399
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36416
    * **Minimum Provider Version**: 8.16.0
1. [x] `RedshiftPauseClusterOperatorAsync` 
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1399
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36416
    * **Minimum Provider Version**: 8.16.0
1. [x] `BatchOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36523
    * **Minimum Provider Version**: 8.17.0
1. [x] `RedshiftSQLOperatorAsync`
    * **Note**: deprecated in OSS airflow
    * **Action**: keep it as it is
    * **Deprecation PR**: -
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [x] `SageMakerProcessingOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36658
    * **Minimum Provider Version**: 8.17.0
1. [x] `SageMakerTransformOperatorAsync`
    * **Note**: minor difference, around `end_time`
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36680
    * **Minimum Provider Version**: 8.17.0
1. [x] `SageMakerTrainingOperatorAsync` (WIP)
    * **Note**: minor difference, after if `self.print_log`
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1463
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36685
    * **Minimum Provider Version**:
1. [x] `RedshiftDataOperatorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1455
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36586
    * **Minimum Provider Version**: 8.17.0

**Comment by phanikumv** [comment]
Refer to https://github.com/apache/airflow/pull/36523

**Comment by Lee-W** [comment]
1. [ ] `EmrContainerSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1390
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [ ] `EmrStepSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1390
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [ ] `EmrJobFlowSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1406
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**:
1. [ ] `RedshiftClusterSensorAsync` 👷
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: 
    * **Minimum Provider Version**: 
1. [ ] `BatchSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1391
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [ ] `S3KeySensorAsync` 👷
    * **Note**: different
    * **Action**: check the difference in detail
    * **Deprecation PR**: 
    * **OSS Airflow PR**:
    * **Minimum Provider Version**:
2. `S3KeySizeSensorAsync` 👷
    * **Note**: different, deprecated in OSS airflow
    * **Action**: fallback S3KeySizeSensorAsync  to S3KeySensor as suggested in https://github.com/apache/airflow/pull/22737
    * **Deprecation PR**: 
    * **OSS Airflow PR**: 
    * **Minimum Provider Version**: 
3. `S3KeysUnchangedSensorAsync`
    * **Note**: mostly the same
    * **Action**: deprecate directly
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1398
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36363
    * **Minimum Provider Version**: 8.15.0
4. `S3PrefixSensorAsync`
    * **Note**: already deprecated
    * **Action**: -
    * **Deprecation PR**: -
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [ ] `EmrContainerOperatorAsync`
    * **Note**: 
    * **Action**: 
    * **Deprecation PR**: 
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
1. [ ] `RedshiftDeleteClusterOperatorAsync`, `RedshiftResumeClusterOperatorAsync`, `RedshiftPauseClusterOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1399
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36416
    * **Minimum Provider Version**: TBD
1. [ ] `BatchOperatorAsync` 👷
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36523
    * **Minimum Provider Version**: TBD
1. [ ] `RedshiftSQLOperatorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: 
    * **Minimum Provider Version**: 
1. [ ] `SageMakerProcessingOperatorAsync`
    * **Note**: minor difference, check the state before deferring
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
2. `SageMakerTransformOperatorAsync`
    * **Note**: minor difference, around `end_time`
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -
3. `SageMakerTrainingOperatorAsync`
    * **Note**: minor difference, after if `self.print_log`
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**: 
    * **Minimum Provider Version**:
1. [ ] `RedshiftDataOperatorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: 
    * **OSS Airflow PR**:
    * **Minimum Provider Version**:

**Comment by Lee-W** [comment]
got some push back in https://github.com/apache/airflow/pull/36416 and https://github.com/apache/airflow/pull/36523. already started the discussion with the community. started working on operator we've not yet contributed back instead of missing the check

**Comment by Lee-W** [comment]
Add draft https://github.com/apache/airflow/pull/36578 and https://github.com/apache/airflow/pull/36550

**Comment by Lee-W** [comment]
Add draft https://github.com/apache/airflow/pull/36585

**Comment by Lee-W** [comment]
Wrap up https://github.com/apache/airflow/pull/36578 and add https://github.com/apache/airflow/pull/36658

**Comment by Lee-W** [comment]
* Depreaction PR in Review
    * EmrJobFlowSensorAsync
    * S3KeysUnchangedSensorAsync
    * EmrContainerOperatorAsync
* Wait for upstream review
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync
* Work in Progess
    * SageMakerTrainingOperatorAsync
    * RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync
* Wait for upstream release
    * RedshiftClusterSensorAsync
    * RedshiftDeleteClusterOperatorAsync, RedshiftResumeClusterOperatorAsync, RedshiftPauseClusterOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 11th

* Deprecation PR in Review
    * EmrJobFlowSensorAsync
    * RedshiftDeleteClusterOperatorAsync, RedshiftResumeClusterOperatorAsync, RedshiftPauseClusterOperatorAsync
* Work in progress
    * SageMakerTrainingOperatorAsync
    * RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync
* Wait for the upstream release
    * RedshiftClusterSensorAsync
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 15th

* Deprecation PR in Review
    * EmrJobFlowSensorAsync
    * RedshiftDeleteClusterOperatorAsync, RedshiftResumeClusterOperatorAsync, RedshiftPauseClusterOperatorAsync
* Wait for upstream review  
    * SageMakerTrainingOperatorAsync  
* Work in progress
    * RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync
* Wait for the upstream release
    * RedshiftClusterSensorAsync
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 16th

* Deprecation PR in Review
    * EmrJobFlowSensorAsync
    * RedshiftDeleteClusterOperatorAsync, RedshiftResumeClusterOperatorAsync, RedshiftPauseClusterOperatorAsync
* Wait for upstream review
    * SageMakerTrainingOperatorAsync  
    * RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync
* Wait for the upstream release
    * RedshiftClusterSensorAsync
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 17th

* Wait for upstream review
    * [SageMakerTrainingOperatorAsync ](https://github.com/apache/airflow/pull/36685)
    * [RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync](https://github.com/apache/airflow/pull/36586)
* Wait for the upstream release
    * RedshiftClusterSensorAsync
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 19th

* Wait for upstream review
    * [SageMakerTrainingOperatorAsync ](https://github.com/apache/airflow/pull/36685)
* Wait for the upstream release
    * RedshiftDataOperatorAsync, RedshiftSQLOperatorAsync
    * RedshiftClusterSensorAsync
    * S3KeySensorAsync, S3KeySizeSensorAsync
    * BatchOperatorAsync
    * SageMakerProcessingOperatorAsync
    * SageMakerTransformOperatorAsync

**Comment by Lee-W** [comment]
As of Jan 14th

* WIP
    * [SageMakerTrainingOperatorAsync](https://github.com/apache/airflow/pull/36685)
    *  RedshiftSQLOperatorAsync
* Wait for the upstream release (deprecation PR created)
    * [RedshiftDataOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [RedshiftClusterSensorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [S3KeySensorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [BatchOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [SageMakerProcessingOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [SageMakerTransformOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)

**Comment by Lee-W** [comment]
After working on `RedshiftSQLOperatorAsync` a bit, I think we should not deprecate it and keep it as it is just like the snowflake operator instead.

**Comment by Lee-W** [comment]
As of Jan 29th

* WIP
    * [SageMakerTrainingOperatorAsync](https://github.com/apache/airflow/pull/36685)
* Wait for the upstream release (deprecation PR created)
    * [RedshiftDataOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [RedshiftClusterSensorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [S3KeySensorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [BatchOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [SageMakerProcessingOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)
    * [SageMakerTransformOperatorAsync](https://github.com/astronomer/astronomer-providers/pull/1455)

**Comment by phanikumv** [comment]
Waiting for OSS provider release
