### ISSUE TITLE
Deprecate core async sensors

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1413]
**Is your feature request related to a problem? Please describe.**

 as most of the functionality has been contributed back to OSS airflow, we're going to leverage the code there and deprecate this project

**Describe the solution you'd like**

1. Contribute the delta to the OSS provider
2. Point the astronomer provider to the OSS provider
3. Do the release and wait for a month or so before we remove the astronomer provider in a major release

**Describe alternatives you've considered**

**Additional context**

-----

## Current Progress
* Number of operator changes on OSS airflow needed: 2
* Number of operators to deprecate: 2

1. [ ] `FileSensorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**:
    * **OSS Airflow PR**: - https://github.com/apache/airflow/pull/36840
    * **Minimum Provider Version**: -
1. [ ] `ExternalTaskSensorAsync`
    * **Note**: minor difference, difference in DagStateTrigger
    * **Action**: dig deeper
    * **Deprecation PR**:
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36916
    * **Minimum Provider Version**: -
1. [x] `ExternalDeploymentTaskSensorAsync`
    * **Note**: other, astro-specific operator
    * **Action**: Do not contribute back to OSS as it is Astronomer specific. Keep it as it is.
    * **Deprecation PR**: -
    * **OSS Airflow PR**: -
    * **Minimum Provider Version**: -

**Comment by pankajastro** [comment]
This will be released as core airflow release

**Comment by phanikumv** [comment]
PR https://github.com/apache/airflow/pull/36840 created for `FileSensorAsync` 

`ExternalTaskSensorAsync` is WIP

**Comment by phanikumv** [comment]
@pankajastro can you add the PR created for this issue in the above note

**Comment by pankajastro** [comment]
PR has been merged. closing it
