### ISSUE TITLE
Deprecate kubernetes async provider

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1418]
**Is your feature request related to a problem? Please describe.**

 as most of the functionality has been contributed back to OSS airflow, we're going to leverage the code there and deprecate this project

**Describe the solution you'd like**

1. Contribute the delta to the OSS provider
2. Point the astronomer provider to the OSS provider
3. Do the release and wait for a month or so before we remove the astronomer provider in a major release

**Describe alternatives you've considered**

**Additional context**

-----

## Current Progress
* Number of operator changes on OSS airflow needed: 1
* Number of operators to deprecate: 1

1. [ ] `KubernetesPodOperatorAsync`
    * **Note**: different, using different triggerer
    * **Action**: dig deeper
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1465
    * **OSS Airflow PR**: 
    1. https://github.com/apache/airflow/pull/37279
    2. https://github.com/apache/airflow/pull/37363
    3. https://github.com/apache/airflow/pull/37514
    4. https://github.com/apache/airflow/pull/37454
    5. https://github.com/apache/airflow/pull/37508
    * **Minimum Provider Version**:

**Comment by pankajastro** [comment]
OSS KPO prints the container log at the end of execution, specifically when the execute_complete method runs. I am considering logging the container log in the trigger, but doing so would result in the log being printed twice: once when the trigger runs and again from the execute_complete method.

I have a rough implementation in progress, which still needs testing and the addition of the parameter periodic_container_log. This parameter, when set to True, will also print the log from the trigger and keep it False by default.

https://github.com/apache/airflow/compare/main...astronomer:airflow:kpo_logging?expand=1

**Comment by pankajkoti** [comment]
We verified that PR https://github.com/apache/airflow/pull/37279 is able to fetch the container logs periodically.

<img width="1728" alt="Screenshot 2024-02-12 at 12 49 29 PM" src="https://github.com/astronomer/astronomer-providers/assets/10206082/25af42f5-d869-4826-a38d-4d8c672456f1">

**Comment by pankajastro** [comment]
OSS PR Fix: 
- https://github.com/apache/airflow/pull/37279
- https://github.com/apache/airflow/pull/37454
- https://github.com/apache/airflow/pull/37363
- https://github.com/apache/airflow/pull/37508
- https://github.com/apache/airflow/pull/37514

**Comment by pankajkoti** [comment]
I have linked the above PRs in the description above.
