### ISSUE TITLE
Deprecate sftp async provider

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1419]
**Is your feature request related to a problem? Please describe.**

 as most of the functionality has been contributed back to OSS airflow, we're going to leverage the code there and deprecate this project

**Describe the solution you'd like**

1. Contribute the delta to the OSS provider
2. Point the astronomer provider to the OSS provider
3. Do the release and wait for a month or so before we remove the astronomer provider in a major release

**Describe alternatives you've considered**

**Additional context**

-----

## Current Progress
* Number of operator changes on OSS airflow needed: 1
* Number of operators to deprecate: 1

1. [ ] `SFTPSensorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1470
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/37117
    * **Minimum Provider Version**:

**Comment by pankajkoti** [comment]
Waiting for OSS provider release
