### ISSUE TITLE
Deprecate http async provider

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#1420]
**Is your feature request related to a problem? Please describe.**

 as most of the functionality has been contributed back to OSS airflow, we're going to leverage the code there and deprecate this project

**Describe the solution you'd like**

1. Contribute the delta to the OSS provider
2. Point the astronomer provider to the OSS provider
3. Do the release and wait for a month or so before we remove the astronomer provider in a major release

**Describe alternatives you've considered**

**Additional context**

-----

## Current Progress
* Number of operator changes on OSS airflow needed: 1
* Number of operators to deprecate: 1

1. [x] `HttpSensorAsync`
    * **Note**: not yet contributed back
    * **Action**: contribute back
    * **Deprecation PR**: https://github.com/astronomer/astronomer-providers/pull/1459
    * **OSS Airflow PR**: https://github.com/apache/airflow/pull/36904
    * **Minimum Provider Version**: 4.9.0

**Comment by vatsrahul1001** [comment]
Raised [PR](https://github.com/apache/airflow/pull/36904) in OSS

**Comment by phanikumv** [comment]
@vatsrahul1001 to link the relevant PR for this

**Comment by pankajkoti** [comment]
PRs linked and merged. Closing the issue.
