### ISSUE TITLE
Update public documentation regarding deprecation of operators

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#1434]
Highlight 1.19 related notes in public documentation for astronomer-providers.
It's essential for us to closely coordinate with the documentation and CRE teams 
throughout the release to ensure seamless communication. In our GitHub repo docs, 
we should suggest using Async operators from OSS repo instead of using ours.

**Comment by vatsrahul1001** [comment]
With the `SnowflakeSqlApiHookAsync`, we neglected to specify the region while constructing the [URL](https://github.com/astronomer/astronomer-providers/blob/ec3e53967e4c608a782f3bd1add59591b05ffad9/astronomer/providers/snowflake/hooks/snowflake_sql_api.py#L192). In the connection, we were appending the region to the account name only. However, in the OSS hook, the [URL](https://github.com/apache/airflow/blob/347373986c378a3c7fd4cf85336d0c419a51991e/airflow/providers/snowflake/hooks/snowflake_sql_api.py#L211) is constructed using the region. Therefore, we can now update the region field in the connection and remove the region from the account field.

**Comment by pankajkoti** [comment]
Created draft PR: https://github.com/astronomer/astronomer-providers/pull/1468
