### ISSUE TITLE
Document Async Redshift Operator integration test findings

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#146]
Some of the findings of Integration Testing on the Async Redshift Operator are :

- While creating the cluster make sure it is created with a  unique name along with a cluster snapshot
- If it is created with previous name make sure there is a snapshot in the cluster
- Delete the cluster along with created snapshot (it is not suggested because this snapshot storage is chargeable)

We need this to be documented within the Operator code docstrings so that users are well informed.

**Comment by bharanidharan14** [comment]
Created PR for this task

https://github.com/astronomer/astronomer-providers/pull/172
