### ISSUE TITLE
Fix example_external_deployment_task_sensor DAG

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/astronomer-providers#1461]
We need to fix example_external_deployment_task_sensor DAG as its still using  [ASTRONOMER_KEY_ID](https://github.com/astronomer/astronomer-providers/blob/63b042109abd27905813adea915dc1d02610126f/astronomer/providers/core/example_dags/example_external_deployment_task_sensor.py#L17) and [ASTRONOMER_KEY_SECRET](https://github.com/astronomer/astronomer-providers/blob/63b042109abd27905813adea915dc1d02610126f/astronomer/providers/core/example_dags/example_external_deployment_task_sensor.py#L18C36-L18C57) which we do not use any more, need to replace this with token

**Comment by phanikumv** [comment]
cc @pankajastro

**Comment by pankajastro** [comment]
Draft PR: https://github.com/astronomer/astronomer-providers/pull/1484

**Comment by pankajastro** [comment]
Tested and marked PR as ready for review. Appreciate your feedback
