### ISSUE TITLE
Documentation for Hive (Local) and Amazon Hive connection

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#164]
**Acceptance Criteria**:

- [x] Documentation steps to setup Hive (Local) 
- [x] Documentation steps for Amazon Hive connection

**Comment by rajaths010494** [comment]
[Hive local Installation and connection ](https://www.notion.so/astronomerio/Hive-Local-Installation-and-Connection-02f978a91b4d44f4a2024b05441da572)

[Amazon Hive Connection](https://www.notion.so/astronomerio/Amazon-Hive-Connections-4072a88bbb1349beaca4204ea5a8e90d)

**Comment by phanikumv** [comment]
@pankajkoti please execute the steps and check whether everything is covered. We can then close this issue.

**Comment by pankajkoti** [comment]
@phanikumv I have followed the steps for Amazon Hive Connection and made some minor modifications which I felt could help more. Do I also need to review Hive local installation and connection or is it reviewed by someone already?

**Comment by phanikumv** [comment]
local hive is not needed to be reviewed for now, as Amazon Hive connection is working.
