### ISSUE TITLE
Automate Redshift cluster creation  

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#165]
Automate Redshift cluster creation step in example dag of operator RedshiftPauseClusterOperatorAsync and RedshiftSQLOperatorAsync. Currently, the cluster creation and cluster deletion manual i.e both examples assume that there is already a Redshift cluster running in AWS and once the example dag execution is complete someone will manually delete it or it will keep running so it makes sense to add the first task in DAG to create cluster and last task to delete it. Currently, we do not have any operator to create a redshift cluster and delete it so for time being we can use BashOperator or PythonOperator. This change will make both DAGs running in more automated way

**Acceptance Criteria:**
- [x] example dag for RedshiftPauseClusterOperatorAsync operator should be self-sufficient 
- [x] example dag for RedshiftSQLOperatorAsync operator should be self-sufficient

**Comment by pankajastro** [comment]
`example_async_redshift_cluster_management` is now running standalone but for `example_async_redshift_sql` getting permission issue

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/usr/local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/amazon/aws/operators/redshift_sql.py", line 51, in execute_complete
    raise AirflowException(msg)
airflow.exceptions.AirflowException: Error: CREATE OR REPLACE FUNCTION janky_sleep (x float) RETURNS bool IMMUTABLE as $$
                from time import sleep
                sleep(x)
                return True
            $$ LANGUAGE plpythonu; query Failed due to, ERROR: permission denied for language plpythonu
```

**Comment by pankajastro** [comment]
To create UDF in plpythonu (Python) language and run it require a special privilege because it is not a trusted language for this use case. run `select * from pg_language` in query console to list language and check trusted or not.So using plpgsql procedure and looping 500k times to delay.  https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_FUNCTION.html .

**Comment by phanikumv** [comment]
Can you please update on the status for RedshiftSQLOperatorAsync
