### ISSUE TITLE
[SPIKE/RESEARCH] Async `AzureDataFactoryPipelineRunStatusSensor`

### ISSUE THREAD

**Issue by kaxil** [astronomer/astronomer-providers#185]
Research options on how to create an Async version of [`AzureDataFactoryPipelineRunStatusSensor`](https://airflow.apache.org/docs/apache-airflow-providers-microsoft-azure/stable/_api/airflow/providers/microsoft/azure/sensors/data_factory/index.html#airflow.providers.microsoft.azure.sensors.data_factory.AzureDataFactoryPipelineRunStatusSensor): 

**Acceptance Criteria:**
Document possible options and selection reasons for a particular library in this GitHub issue via a Summary comment.

Find a Python library that supports async implementation for Azure data factory if the official library does not support it.

**Comment by bharanidharan14** [comment]
-  The official Azure SDK for python supports Async version implementation for AzureDataFactory, so we can make use of the official library for (PipelinesOperations, PipelineRunsOperations, Triggers, etc..)

Azure data factory aio library link: [Azure Data factory](https://docs.microsoft.com/en-us/python/api/azure-mgmt-datafactory/azure.mgmt.datafactory.aio.operations?view=azure-python)

Document for creating data factory and pipeline: [Data factory creation](https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-portal)

**Comment by phanikumv** [comment]
@bharanidharan14 I have requested this to be closed yesterday
