### ISSUE TITLE
DRAFT: Add querytag to execute method of snowflake Operator

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/astronomer-providers#189]
The Openlineage adapter for Snowflake can directly read audit info. To add to the richness of the information available for queries run with Airflow, we want each query to able to be mapped back to an Airflow task. 

To do this, we want the SnowflakeOperator to send back a string that contains `airflow_taskid_dagid_trynumber_TIMESTAMP`  as a [Query Tag](https://docs.snowflake.com/en/sql-reference/parameters.html#query-tag) in the query parameters.

*Acceptance Criteria*
- The Snowflake Operator param `parameters` has a default value of `airflow_taskid_dagid_trynumber_TIMESTAMP`  that is set as a query tag in each query, with a max length of 200 characters.
- This parameter shows up when querying Snowflake's [QUERY_HISTORY](https://docs.snowflake.com/en/sql-reference/functions/query_history.html).

**Comment by denimalpaca** [comment]
Note on how this may work:

In the `execute()` method of the `AsyncSnowflakeOperator`, a line of SQL will be added to the query that would look something like: `ALTER SESSION SET query_tag = 'airflow_taskid_dagid_trynumber_TIMESTAMP'`; this sets the query tag at the session level (which is preferable in this case to the user or account level).

**Comment by denimalpaca** [comment]
@rossturk @julienledem and I had a conversation about this query tag work -- we had a thought about moving the SQL statement to alter session into the Snowflake Hook if possible. This would allow the query tag to work for every Snowflake Operator variant (Async, Check, etc...) and provide information to OpenLineage even if the user is using the PythonOperator. Additionally, the query tag could be overwritten by including a `query_tag` argument to `hook_params` in `Airflow>=2.3`.

**Comment by bharanidharan14** [comment]
Me and @denimalpaca connected on this `query_tag` implementation we have decided to add `query_tag` for a session even if the operator sends list of query or single query or multiple query as ';' separated string query. it needs to be added in both `sync` and `async` Snowflake operators

**Comment by julienledem** [comment]
This sounds correct.
can we have a more formal spec of the values in the query tag?
Right now I'm reading `airflow_{taskid}_{dagid}_{trynumber}_{TIMESTAMP}`
IT would be useful if this contained:
- OPENLINEAGE_NAMESPACE
- The DAG name
- The Task name

Are the taskid and the dagid the same thing as their name? In that case I would just add the OPENLINEAGE_NAMESPACE in there.

**Comment by bharanidharan14** [comment]
@julienledem Thanks for the confirmation, I will try to add `OPENLINEAGE_NAMESPACE` as well in the query tag

**Comment by virajmparekh** [comment]
The DAG ID and task ID are different; a unique task in Airflow is defined
by its dag_id, task_id, and try_number. We can probably remove the need to
include timestamp, as the time a query ran is probably already in another
table in Snowflake. So perhaps
`airflow_openlineagens_dagid_taskid_trynumber?`

Also note that the tag can only be 200 characters.

**Comment by bharanidharan14** [comment]
@denimalpaca I Tired the moving the alter session query into the Snowflake Hook, we need some context information to be sent to hook for task id, dag id and its the same so its better to keep the code in same execute method and I have handled for list of query params and ';' separated query params.

**Comment by bharanidharan14** [comment]
pushed the code changes created the draft PR https://github.com/astronomer/astronomer-providers/pull/401

**Comment by bharanidharan14** [comment]
@julienledem @virajmparekh On this issue, I have made some progress with the help of @pankajkoti . I have added `query_tag` to the query, and also added an OL extractor for `async` snowflake operator. We tested this locally by running a flask-based lineage collection server. Airflow is able to emit the lineage event. I am able to view the json event which is emitted after the Airflow task is executed. The `query_tag` is getting recorded in the Snowflake DB. I have attached screenshots of the lineage JSON event and the Snowflake record with `query_tag` for your reference. While testing this locally, we however are not seeing the `query_tag` in the lineage event. If this requirement is only for sync, then I can add query_tag in OSS and make PR. If the requirement is also for async snowflake operator we need to time to investigate and add `query_tag` to lineage JSON
<img width="804" alt="Screenshot 2022-06-07 at 5 54 19 PM" src="https://user
[2022-06-03-example_snowflake.snowflake_op_sql_list.json.zip](https://github.com/astronomer/astronomer-providers/files/8853154/2022-06-03-example_snowflake.snowflake_op_sql_list.json.zip)
-images.githubusercontent.com/94612827/172378248-83fdc658-9d7a-492b-b541-84525e9281c7.png">

**Comment by bharanidharan14** [comment]
[2022-06-03-example_snowflake.snowflake_op_sql_list.json.zip](https://github.com/astronomer/astronomer-providers/files/8853551/2022-06-03-example_snowflake.snowflake_op_sql_list.json.zip)
<img width="804" alt="Screenshot 2022-06-07 at 5 54 19 PM" src="https://user-images.githubusercontent.com/94612827/172391850-cdd7fe45-459c-4a10-9c69-fa070b701843.png">

**Comment by virajmparekh** [comment]
@bharanidharan14 - great work! Thanks for the effort here.

I think that's fine; per a conversation with @julienledem ; it is not yet implemented on the OL side. This should go in the async version as it helps build the story that the Astronomer Provider is the "enterprise grade" snowflake provider.

**Comment by phanikumv** [comment]
why is this reopened ? Is there any pending work on providers side?

**Comment by bharanidharan14** [comment]
Addressed PR review comments still code coverage needs to be fixed

**Comment by phanikumv** [comment]
Please close in case everything is implemented.
