### ISSUE TITLE
Certification "Apache Airflow DAG Authoring" for Pankaj

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#190]

**Comment by pankajkoti** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Airflow-Providers-Team-61a89ee7fbf048001dc8378d/issues/astronomer/astronomer-providers/190?planning-poker) with ZenHub @phanikumv

**Comment by pankajkoti** [comment]
Had started taking the course and hoping to finish the preparation course today.

**Comment by pankajkoti** [comment]
Completed the course and finished the exam with a score of 93% (70/75). Took a look at the questions I answered wrong and understood those.
<img width="865" alt="Screenshot 2022-04-06 at 2 39 20 PM" src="https://user-images.githubusercontent.com/10206082/161960513-743006f9-a9f9-417d-9e06-faaa77c47dc5.png">

**Comment by pankajastro** [comment]
Congratulations @pankajkoti
