### ISSUE TITLE
Enhance `EMRContainerSensorAsync` example DAG

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#199]
Change EMRContainerSensor example DAG to 

- create EMR EKS cluster
- read virtual cluster id
- read job role arn
- run the Async EMRContainerSensor
- delete the cluster

**Comment by bharanidharan14** [comment]
Add task to create virtual cluster, and delete the cluster task in example to be self sufficient DAG

**Comment by bharanidharan14** [comment]
https://github.com/astronomer/astronomer-providers/blob/emr_container_example_dag/astronomer/providers/amazon/aws/example_dags/example_emr_eks_containers_job.py

Need to test in staging environment
