### ISSUE TITLE
[Integration Tests]:Increase execution timeout for example dag

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#246]
Since the number of example dag is increasing we will have to increase execution in order to run it as an integration test. the current execution time is 30 min

**Comment by pankajkoti** [comment]
@pankajastro had already started working on it and has a PR open for it: https://github.com/astronomer/astronomer-providers/pull/249#pullrequestreview-947053876

Hence, assigning the issue to @pankajastro 

Also, Pankaj Singh and I had a session today where he explained me our deployment and runtime architecture for these example DAGs. Thank you so much for that @pankajastro

**Comment by phanikumv** [comment]
This change is completed
