### ISSUE TITLE
[SPIKE/RESEARCH] Async `NamedHivePartitionSensor `

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#248]
**Acceptance Criteria:**
Document possible options and selection reasons for a particular library in this GitHub issue via a Summary comment.

Find a Python library that supports async implementation for NamedHivePartitionSensor if the official library does not support it.

Ensure that connection is set up and working

**Comment by pankajastro** [comment]
The implementation pattern for this sensor is very similar to `HivePartitionSensor` 
Tested the sync version example
We have decided to use `impala`
