### ISSUE TITLE
Upgrade staging airflow version

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#254]
- Make changes to use new airflow image in our staging deployment.
- Enable multi stage deployment

**Comment by phanikumv** [comment]
@pankajastro please update with the latest status on this.

**Comment by pankajastro** [comment]
staging instances work only with airflow image i.e `ap-airflow:x.y.z`
astro-cloud instances work only with runtime image i.e `astro-runtime:z.y.x`
Initial PR: https://github.com/astronomer/astronomer-providers/pull/245
Final fix: https://github.com/astronomer/astronomer-providers/pull/244
