### ISSUE TITLE
Fix HivePartitionSensor example DAG

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#265]
- Change the docker file to copy the hive,  hadoop binaries and JDK 8 to airflow worker
- Deploy on staging and test the DAG end to end

**Comment by rajaths010494** [comment]
Could not open connection to the HS2 server. Please check the server URI and if the URI is correct, then ask the administrator to check the server status.
Error: Could not open client transport with JDBC Uri: jdbc:hive2://ec2-18-222-146-86.us-east-2.compute.amazonaws.com:10000/default;auth=none: java.net.ConnectException: Connection timed out (Connection timed out) (state=08S01,code=0)
beeline> No current connection

**Comment by rajaths010494** [comment]
RUN apt-add-repository 'deb http://security.debian.org/debian-security stretch/updates main'
RUN apt-get update && apt-get install -y openjdk-8-jdk 
used openjdk-8-jdk to install and openjdk issue is resolved.
Ran the pipeline it's working fine. 
Will be raising the PR today.
