### ISSUE TITLE
Migrate providers team AWS users to OKTA

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#272]
The users via SSO are maintained centrally in OKTA. We can create a single user for "Providers Integration Test", the access key for which we can use in our Staging env and Gen2 Cloud so we can isolate the application usages.

In absence of this, the access keys that we use in our integration test are associated with a "IAM User account".

**Comment by pankajkoti** [comment]
Please let me know once this is done. I can take care of updating the required variables & connection settings with the new credentials on Staging environment for our integration tests.

**Comment by phanikumv** [comment]
This is completed . Created a service account providers-integration-test, and ensured that there are no permission issues in any of existing DAG
