### ISSUE TITLE
Integration DAG's : Test in astro-cloud

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#274]
- Create an astro-cloud instance
- Run the deployment
- Execute all the integration DAG

**Comment by pankajkoti** [comment]
We have moved the DAGs on Astro Cloud. However, a few DAGs are failing with limited error details. Need to investigate the errors.
Additionally, we're also missing credentials for Azure DAGs which need to be taken from @bharanidharan14
