### ISSUE TITLE
[SPIKE/RESEARCH]  `Azure Functions` and `Azure Service Bus`

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#276]
Acceptance Criteria:
Document possible options and selection reasons for a particular library in this GitHub issue via a Summary comment.
Find a Python library that supports **Synchronous** implementation for [Azure functions](https://azure.microsoft.com/en-in/services/functions/) and [Azure Service Bus ](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-messaging-overview) if the official library does not support it.

Ensure that connection is set up and working.

**Comment by bharanidharan14** [comment]
Started working on the Azure service bus, installed the package 
-` pip install azure-servicebus`
-` pip install azure-identity`
Running the sample sync code version

**Comment by bharanidharan14** [comment]
Tried out few examples in service bus and azure functions, captured few in nation page
Notion page link:
Service Bus: https://www.notion.so/astronomerio/Azure-Service-Bus-130e1721f68f4526b20d081798dd66da
Azure Functions: https://www.notion.so/astronomerio/Azure-Functions-f249d866785b43fdb5610c25088e3e1e

**Comment by bharanidharan14** [comment]
Updated the list service bus Async operators in the notion page

https://www.notion.so/astronomerio/Azure-Service-Bus-130e1721f68f4526b20d081798dd66da

**Comment by phanikumv** [comment]
@bharanidharan14 please close this in case your research is done.
