### ISSUE TITLE
Use consistent method to fetch env variable Value

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#307]
we should either use `os.environ.get` or `os.getenv` across the repo to fetch the env variable value, not both

**Comment by pankajkoti** [comment]
I would have a slight preference towards using os.getenv if everyone agrees to it.
No specific reason, just less characters.

**Comment by pankajastro** [comment]
> I would have a slight preference towards using os.getenv if everyone agrees to it. No specific reason, just less characters.

Ok, I'll make it to use `os.getenv`
