### ISSUE TITLE
Tasks failing without writing any logs

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#351]
Some tasks are failing without writing any logs.

Possible reason might be 
Imports of heavy libraries at module level might cause DAG processing timeout errors.
To avoid this, we need to delay of imports to the specific operator scope.

Reference: https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#top-level-python-code

However we need to investigate in detail.

**Comment by pankajkoti** [comment]
We have a Zendesk ticket created for this issue: https://astronomer.zendesk.com/agent/tickets/9862

**Comment by bharanidharan14** [comment]
Since issue is not being observed for weeks, so closing the issue
