### ISSUE TITLE
S3KeySensorAsync templated bucket_key

### ISSUE THREAD

**Issue by patryk126p** [astronomer/astronomer-providers#362]
**Is your feature request related to a problem? Please describe.**
I would like to transition from `S3KeySensor` to `S3KeySensorAsync` but I've noticed that async version in astronomer-providers doesn't allow for templated airflow variables in `bucket_key` param

**Describe the solution you'd like**
As far as I can see it should be as simple as adding same line as in `S3KeySensor` in class definition:
```
template_fields: Sequence[str] = ('bucket_key', 'bucket_name')
```

**Describe alternatives you've considered**
-

**Additional context**
-

Please enable templating `bucket_key` in `S3KeySensorAsync`

**Comment by kaxil** [comment]
Fixed and released in 1.3.1
