### ISSUE TITLE
Test the integration DAGs on Stellar

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#379]
Test the integration DAGs with Stellar Executor using astro cloud dev alpha image

**Comment by rajaths010494** [comment]
Created a example_dag to get executor,  command  `airflow config get-value core executor` and deploy in dev env and run the example dag to check for stellar executor.

**Comment by rajaths010494** [comment]
2022-06-16, 12:03:03 UTC] {taskinstance.py:1394} INFO - Marking task as SUCCESS. dag_id=example_gcp_dataproc, task_id=create_cluster, execution_date=20220616T120000, start_date=20220616T120005, end_date=20220616T120303
[2022-06-16, 12:03:03 UTC]    INFO | Task exited with return code 0
[2022-06-16, 12:03:03 UTC]   ERROR | Failed to execute task <object object at 0x7f412c364740> is not a valid _MethodDefault.
Traceback (most recent call last):
  File “/usr/local/lib/python3.9/site-packages/stellar/runner/subprocess.py”, line 254, in __init__
    parsed_args.func(parsed_args)
  File “/usr/local/lib/python3.9/site-packages/airflow/cli/cli_parser.py”, line 51, in command
    return func(*args, **kwargs)
  File “/usr/local/lib/python3.9/site-packages/airflow/utils/cli.py”, line 99, in wrapper
    return f(*args, **kwargs)
  File “/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py”, line 372, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File “/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py”, line 181, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
  File “/usr/local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py”, line 239, in _run_task_by_local_task_job
    run_job.run()
  File “/usr/local/lib/python3.9/site-packages/airflow/jobs/base_job.py”, line 244, in run
    self._execute()
  File “/usr/local/lib/python3.9/site-packages/airflow/jobs/local_task_job.py”, line 133, in _execute
    self.handle_task_exit(return_code)
  File “/usr/local/lib/python3.9/site-packages/airflow/jobs/local_task_job.py”, line 171, in handle_task_exit
    self._run_mini_scheduler_on_child_tasks()
  File “/usr/local/lib/python3.9/site-packages/airflow/utils/session.py”, line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File “/usr/local/lib/python3.9/site-packages/airflow/jobs/local_task_job.py”, line 253, in _run_mini_scheduler_on_child_tasks
    partial_dag = task.dag.partial_subset(
  File “/usr/local/lib/python3.9/site-packages/airflow/models/dag.py”, line 2013, in partial_subset
    dag.task_dict = {
  File “/usr/local/lib/python3.9/site-packages/airflow/models/dag.py”, line 2014, in <dictcomp>
    t.task_id: _deepcopy_task(t)
  File “/usr/local/lib/python3.9/site-packages/airflow/models/dag.py”, line 2011, in _deepcopy_task
    return copy.deepcopy(t, memo)
  File “/usr/local/lib/python3.9/copy.py”, line 153, in deepcopy
    y = copier(memo)
  File “/usr/local/lib/python3.9/site-packages/airflow/models/baseoperator.py”, line 1150, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
  File “/usr/local/lib/python3.9/copy.py”, line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File “/usr/local/lib/python3.9/copy.py”, line 264, in _reconstruct
    y = func(*args)
  File “/usr/local/lib/python3.9/enum.py”, line 384, in __call__
    return cls.__new__(cls, value)
  File “/usr/local/lib/python3.9/enum.py”, line 702, in __new__
    raise ve_exc
ValueError: <object object at 0x7f412c364740> is not a valid _MethodDefault
When running example dags on stellar executor there is error occuring after the task is completed and marked for success.
Dags failing with this issue -[ example_async_adf_run_pipeline](https://astronomer.astronomer-dev.run/dndvvlgr/dags/example_async_adf_run_pipeline/grid), [example_gcp_dataproc](https://astronomer.astronomer-dev.run/dndvvlgr/dags/example_gcp_dataproc/grid), [example_hive_dag](https://astronomer.astronomer-dev.run/dndvvlgr/dags/example_hive_dag/grid),[ example_livy_operator](https://astronomer.astronomer-dev.run/dndvvlgr/dags/example_livy_operator/grid)

**Comment by rajaths010494** [comment]
Tested on 6.0.0-alpha16  the same error occured on Azure example dag. Reported it to kelechi.

**Comment by kelechi2020** [comment]
This is related to a known open issue https://github.com/astronomer/stellar/issues/193 
Following up the dev team for updates.
This should be fixed after  https://github.com/astronomer/stellar/issues/193 is closed.

**Comment by ernest-kr** [comment]
@rajaths010494 Can you please use the 5.1.0-alpha2 build to validate this instead of the 6.0.0. We no longer want to use 6.0.0 for stellar.

**Comment by rajaths010494** [comment]
Few dags which are failing doesn't have any logs to debug.
Other dags are running fine with no issues.
Have reported it to @kelechi2020 .

**Comment by rajaths010494** [comment]
Retesting it today

**Comment by rajaths010494** [comment]
https://github.com/astronomer/stellar/issues/225 Git issue has been raised for the task logs not showing up for DAGS that trigger jobs in external clusters

**Comment by phanikumv** [comment]
Still waiting on astronomer/stellar#225

**Comment by pankajkoti** [comment]
3 issues have been identified by the Stellar team and work is still in progress on their end. We're waiting for their resolutions.

**Comment by rajaths010494** [comment]
Logging retrieval, which the associated PR should solve. Needs an integration test, which is almost done.
Log shipping - permissions. #232 will track that.

**Comment by kelechi2020** [comment]
The Spark/Pig jobs are failing actually,. Let's debug this further after the log fix land so we could actually have some facts .Will create a follow up issue for it after the logs permissions issues are fixed  [#230](https://github.com/astronomer/stellar/pull/230) [#232](https://github.com/astronomer/stellar/pull/232) 

CC: @rajaths010494

**Comment by kelechi2020** [comment]
@rajaths010494 a [Support reading logs for multiple try_numbers (](https://github.com/astronomer/stellar/commit/5abbcb6c2ace7a4a2f5e709c4d4402e9762e9df3)
 is made on stellar  using `5.1.0-alpha11`  image.
 Please help verify fix on integration dags.
 CC: @ernest-kr

**Comment by rajaths010494** [comment]
Astro Dev env was down. I will test it once it's fixed.

**Comment by rajaths010494** [comment]
xhttps://github.com/astronomer/harmony/issues/255

**Comment by rajaths010494** [comment]
After upgrading to new image 5.1.0-alpha11 still i am seeing error and able to find logs

**Comment by kelechi2020** [comment]
Taking a close look: 

There happen to be no migration ran/triggered from that indicated an upgrade to the base image to 5.1.0-alpha11 - Looking at the pods created
![image](https://user-images.githubusercontent.com/25426248/181450167-93a6cd53-9c3d-4cb6-b6d1-f316ab9fc398.png)


This is blocked pending when we can have https://github.com/astronomer/harmony/issues/255  up so we can directly create an alpha11 image deployment directly from cloud UI.

CC: @rajaths010494

**Comment by bharanidharan14** [comment]
Waiting for the  astronomer/harmony#255 issue to be addressed

**Comment by kelechi2020** [comment]
https://github.com/astronomer/harmony/issues/255 is now fixed on dev cloud UI.
Created a healthy deployment on for use t verify logging issues fix .
Deploymenet name: PROVIDERS_INTEGRATION_TEST_ALPHA_13
Deployment workspace: Providers team
CC: @rajaths010494

**Comment by phanikumv** [comment]
Hi @kelechi2020 , currently we are working on a priority task requested by customer. Wont be able to get to this till Thursday.

**Comment by rajaths010494** [comment]
The DAGs ran fine for image `quay.io/astronomer/astro-runtime-dev:5.1.0-alpha19` for the[ deployment](https://cloud.astronomer-dev.io/cl3ucwvgy136181hv46tozooyi/deployments/cl6q0ubdr64552dylncxdytbm). 
There were no issues with DAGs submitting jobs to externals clusters which earlier had issues and are now its working as expected.
[example_livy_operator
](https://astronomer.astronomer-dev.run/dcxdytbm/dags/example_livy_operator/grid)[example_hive_dag](https://astronomer.astronomer-dev.run/dcxdytbm/dags/example_hive_dag/grid)
[example_gcp_dataproc](https://astronomer.astronomer-dev.run/dcxdytbm/dags/example_gcp_dataproc/grid)
