### ISSUE TITLE
Fix mypy and test coverage issues on KPOA

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#381]
Linked PR https://github.com/astronomer/astronomer-providers/pull/139

**Comment by phanikumv** [comment]
Facing issues during testing as we are unable to deploy DAG changes onto astro-cloud 5.0.1

**Comment by phanikumv** [comment]
@pankaj will try using astro-cloud 5.0.2 and update here

**Comment by pankajastro** [comment]
Created new deployment and test
