### ISSUE TITLE
Automated documentation for available operators

### ISSUE THREAD

**Issue by jwitz** [astronomer/astronomer-providers#392]
**Is your feature request related to a problem? Please describe.**

I've received feedback that the CHANGELOG is difficult to parse when users need to learn about available operators and their import statements. We used to maintain a list of these operators on docs.astronomer.io, but with the frequency of `astronomer-providers` releases it was becoming difficult to maintain and risked becoming out-of-date.

**Describe the solution you'd like**

We should have an automated solution for documenting available providers on https://astronomer-providers.readthedocs.io/en/stable/ so that we: 

- Don't have to double-document operators.
- Don't force users to visit the CHANGELOG as a source of truth.

Could we regularly parse the CHANGELOG for new table rows, then upload those entries to a second doc? Or generate a doc directly from source code. 

**Describe alternatives you've considered**

We've tried documenting these operators on docs.astronomer.io, but at this point it doesn't make sense for us to manually update a table with dozens of operators.

**Comment by phanikumv** [comment]
Below is a grep command to bring the list of all operators and sensors in our repo, may be we can use it to autogenerate list of operators and sensors present on our repo.

`(conda_venv) phanikv@Phanis-MBP providers % grep --exclude=\*.rst  -r -e '^class [a-zA-Z]\+[Sensor,Operator]Async([a-zA-Z]\+)'| cut -d ' ' -f 2 | cut -d "(" -f 1 | sort`
AzureDataFactoryPipelineRunStatusSensorAsync
AzureDataFactoryRunPipelineOperatorAsync
BatchOperatorAsync
BigQueryCheckOperatorAsync
BigQueryGetDataOperatorAsync
BigQueryIntervalCheckOperatorAsync
BigQueryTableExistenceSensorAsync
BigQueryValueCheckOperatorAsync
DatabricksRunNowOperatorAsync
DatabricksSubmitRunOperatorAsync
DataprocSubmitJobOperatorAsync
EmrContainerOperatorAsync
EmrContainerSensorAsync
EmrJobFlowSensorAsync
EmrStepSensorAsync
ExternalTaskSensorAsync
FileSensorAsync
GCSObjectExistenceSensorAsync
GCSObjectUpdateSensorAsync
GCSObjectsWithPrefixExistenceSensorAsync
GCSUploadSessionCompleteSensorAsync
GKEStartPodOperatorAsync
HivePartitionSensorAsync
HttpSensorAsync
KubernetesPodOperatorAsync
LivyOperatorAsync
NamedHivePartitionSensorAsync
RedshiftClusterSensorAsync
RedshiftPauseClusterOperatorAsync
RedshiftResumeClusterOperatorAsync
RedshiftSQLOperatorAsync
SnowflakeOperatorAsync

**Comment by kaxil** [comment]
@phanikumv We will need some way to publish this to our Sphinx docs.

Some options that we discussed with the team y'day were:

1. Sphinx parsing itself
2. ast parse + sphinx
3. And the one you have here i.e. Bash + Pre-commit Hook.

cc @pankajastro @pankajkoti @bharanidharan14

**Comment by kaxil** [comment]
@jwitz Until this is done we now also have an entry on the Astronomer Registry.

**Operators**: https://registry.astronomer.io/providers/astronomer-providers?type=Operators
**Sensors**: https://registry.astronomer.io/providers/astronomer-providers?type=Sensors

**Comment by pankajkoti** [comment]
Wrote a python script to generate list of operators and sensors using ast.parse.

Working next on how to generate document from this Python list of operators and sensors.

**Comment by pankajkoti** [comment]
hi @jwitz the docs are available now with the latest release here: https://astronomer-providers.readthedocs.io/en/stable/providers/operators_and_sensors_list.html
