### ISSUE TITLE
Implement Test Provider Connection methods

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#416]
Consolidate tasks from Spike 427 and implement the test connection methods.

- [x] Trino
- [x] Databricks
- [x] AWS
- [x] Azure
- [x] GCP

**Comment by phanikumv** [comment]
Trino test connection has been implemented in https://github.com/apache/airflow/pull/24583

**Comment by phanikumv** [comment]
Databricks test connection has been implemented in https://github.com/apache/airflow/pull/24617

**Comment by phanikumv** [comment]
AWS test connection is already implemented in https://github.com/apache/airflow/pull/24662

**Comment by phanikumv** [comment]
Google cloud test connection has been implemented in https://github.com/apache/airflow/pull/24682

**Comment by phanikumv** [comment]
Azure Wasb Hook test connection has been implemented in https://github.com/apache/airflow/pull/24771

**Comment by phanikumv** [comment]
Azure FileShare test connection has been implemented in https://github.com/apache/airflow/pull/24843

**Comment by pankajkoti** [comment]
Phani discussed the password field issue with Kaxil and it's concluded that the field will be hidden.

**Comment by phanikumv** [comment]
Azure CosmosDB test connection has been implemented in https://github.com/apache/airflow/pull/25018

**Comment by phanikumv** [comment]
Azure Batch test connection has been implemented in apache/airflow#25235

**Comment by phanikumv** [comment]
Azure ContainerInstance test connection has been implemented in apache/airflow#25362

**Comment by phanikumv** [comment]
Closing this as test connection methods have been implemented wherever applicable for the above providers.
