### ISSUE TITLE
[SPIKE/RESEARCH] Test Provider Connections

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#427]
A research task to check which provider connection works/ doesnt work. Split into batches of providers. The outcome of this spike would be to identify all the provider connections for which "Test Connection" doesnt work.

**Comment by pankajastro** [comment]
| Operator/Sensor  | Hook |  Test Conn |
| ------------- | ----------------------------- |--------|
|  | AthenaHook(AwsBaseHook)  | ❌ |
|   | AwsBaseHook(BaseHook)     |  ❌ |
|   | BatchClientHook(AwsBaseHook)| ❌ |
|   | BatchWaitersHook(BatchClientHook)| ❌ |
| | CloudFormationHook(AwsBaseHook)| ❌ |
| | DataSyncHook(AwsBaseHook) | ❌ | 
| | DmsHook(AwsBaseHook) | ❌ |
| | DynamoDBHook(AwsBaseHook) | ❌ |
| | EC2Hook(AwsBaseHook) | ❌ |
| | EksHook(AwsBaseHook) | ❌ |
| | ElastiCacheReplicationGroupHook(AwsBaseHook) | ❌ |
| | EmrHook(AwsBaseHook) | ❌ |
| | GlacierHook(AwsBaseHook) | ❌ |
| | GlueJobHook(AwsBaseHook) | ❌ |
| | GlueCatalogHook(AwsBaseHook) | ❌ |
| | GlueCrawlerHook(AwsBaseHook) | ❌ |
| | FirehoseHook(AwsBaseHook) | ❌ |
| | LambdaHook(AwsBaseHook) | ❌ |
| | AwsLogsHook(AwsBaseHook) | ❌ |
| | QuickSightHook(AwsBaseHook) | ❌ |
| | RdsHook(AwsBaseHook) | ❌ |
| | RedshiftHook(AwsBaseHook) | ❌ |
| | RedshiftDataHook(AwsBaseHook) | ❌ |
| | RedshiftSQLHook(DbApiHook) | :white_check_mark: |
| | S3Hook(AwsBaseHook) | ❌ |
| | SageMakerHook(AwsBaseHook) | ❌ |
| | SecretsManagerHook(AwsBaseHook)| ❌ |
| | SesHook(AwsBaseHook) | ❌ |
| | SnsHook(AwsBaseHook) | ❌ |
| | SqsHook(AwsBaseHook) | ❌ |
| | StepFunctionHook(AwsBaseHook) | ❌ |
| | StsHook(AwsBaseHook) | ❌ |

**Comment by pankajastro** [comment]
Google cloud related test connection button status 

| Operator/Sensor  | Hook | Test Conn status |
| ------------- | ------------- | ------------- |
|  | CloudAutoMLHook(GoogleBaseHook) | ❌ |
| | BigQueryHook(GoogleBaseHook, DbApiHook) | ✅ |
| | BiqQueryDataTransferServiceHook(GoogleBaseHook) | ❌ |
| | BigtableHook(GoogleBaseHook) | ❌ |
| | CloudBuildHook(GoogleBaseHook) | ❌ |
| | CloudComposerHook(GoogleBaseHook) | ❌ |
| | CloudMemorystoreHook(GoogleBaseHook) | ❌  |
| | CloudSQLHook(GoogleBaseHook) | ❌ |
| | CloudDataTransferServiceHook(GoogleBaseHook) | ❌  |
| | ComputeEngineHook(GoogleBaseHook) | ❌ |
| | ComputeEngineSSHHook(SSHHook | ❌ |
| | CloudDataCatalogHook(GoogleBaseHook) | ❌ |
| | DataflowHook(GoogleBaseHook) | ❌ |
| | DataFusionHook(GoogleBaseHook) | ❌ |
| | DataplexHook(GoogleBaseHook) | ❌ |
| | GoogleDataprepHook(BaseHook) | ❌ |
| | DataprocHook(GoogleBaseHook) | ❌ |
| | DataprocMetastoreHook(GoogleBaseHook) | ❌ |
| | DatastoreHook(GoogleBaseHook) | ❌ |
| | CloudDLPHook(GoogleBaseHook) | ❌ |
| | CloudFunctionsHook(GoogleBaseHook) | ❌ |
| | GCSHook(GoogleBaseHook) | ❌ |
| | GoogleDeploymentManagerHook(GoogleBaseHook) | ❌ |
| | CloudKMSHook(GoogleBaseHook) | ❌ |
| | GKEHook(GoogleBaseHook) | ❌ |
| | LifeSciencesHook(GoogleBaseHook) | ❌ |
| | LookerHook(BaseHook) | ❌ |
| | MLEngineHook(GoogleBaseHook) | ❌ |
| | CloudNaturalLanguageHook(GoogleBaseHook) | ❌ |
| | OSLoginHook(GoogleBaseHook) | ❌ |
| | PubSubHook(GoogleBaseHook) | ❌ |
| | SecretsManagerHook(GoogleBaseHook) | ❌ |
| | SpannerHook(GoogleBaseHook) | ❌ |
| | CloudSpeechToTextHook(GoogleBaseHook) | ❌ |
| | StackdriverHook(GoogleBaseHook) | ❌ |
| | CloudTasksHook(GoogleBaseHook) | ❌ |
| | CloudTextToSpeechHook(GoogleBaseHook) | ❌ |
| | CloudTranslateHook(GoogleBaseHook) | ❌ |
| | CloudVideoIntelligenceHook(GoogleBaseHook) | ❌ |
| | CloudVisionHook(GoogleBaseHook) | ❌ |
| | WorkflowsHook(GoogleBaseHook) | ❌ |

We will have to implement the below method in the above hooks
```
    def test_connection(self):
        return True, 'Connection successfully tested'
```

**Comment by pankajastro** [comment]
Snowflake related test connection button status

Operator/Sensor | Hook | Test Conn status
------------------ | ----- | ----------------
| | SnowflakeHook | ✅ 





SnowflakeHook

**Comment by phanikumv** [comment]
TODO: Databricks, ElasticSearch, Slack, Trino and Hive

**Comment by pankajastro** [comment]
Databricks related test connection button status

Operator/Sensor | Hook | Test Conn status
----------------  |  ------   |  -------------
| | DatabricksHook | ❌ 
| | BaseDatabricksHook | ❌ 
| | DatabricksSqlHook | ✅

**Comment by pankajastro** [comment]
ElasticSearch related test connection button status

| Operator/Sensor | Hook | Test Conn status
----------------- | ------ | --------------
| | ElasticsearchHook | ❌

**Comment by pankajastro** [comment]
Slack related test connection button status

| Operator/Sensor | Hook | Test Conn status
|---------------- | ------- | ----------------
| | SlackHook | ❌ 
| | SlackWebhookHook | ❌

**Comment by pankajastro** [comment]
Trino related test connection button status

| Operator/Sensor | Hook | Test Conn status 
| ----------------- | ----- | ----------------
| | TrinoHook | ❌

**Comment by pankajastro** [comment]
Hive related test connection button status

| Operator/Sensor | Hook | Test Conn status
| ----------------- | ------ | ---------------
| | HiveCliHook | ❌ 
| | HiveMetastoreHook | ❌ 
| | HiveServer2Hook | ❌ 

for HiveServer2Hook test button is not disabled because the parent class implement `test_connection` but I feel like we should also implement in  HiveServer2Hook

**Comment by phanikumv** [comment]
@pankajastro please consolidate for which hooks we need add the test_connection method.

**Comment by pankajastro** [comment]
> SnowflakeHook

Updated the comments for all types of above-mentioned provider

**Comment by pankajastro** [comment]
> @pankajastro please consolidate for which hooks we need add the test_connection method.

Updated the comments for all types of above-mentioned provider
