### ISSUE TITLE
[SPIKE/RESEARCH] Finalize approach to find usage metrics of Operators/Sensors

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#428]
Finalize an approach to find out which operators/sensors are most used in astro deployments. 
This would be helpful to focus our efforts to build async operators for the most used operators/sensors.

cc @vikramkoka

**Comment by rajaths010494** [comment]
After checking airflow db found an table `task_instance` which captures the operator ran and state of the individual tasks.
query used `select operator, count(*) as count from task_instance group by operator order by count desc;`

| sl_no | operator                                 | count |
|-------|------------------------------------------|-------|
| 0     | DataprocSubmitJobOperatorAsync           | 35    |
| 1     | GCSCreateBucketOperator                  | 9     |
| 2     | GCSDeleteBucketOperator                  | 8     |
| 3     | DataprocCreateClusterOperatorAsync       | 7     |
| 4     | DataprocDeleteClusterOperatorAsync       | 7     |
| 5     | BigQueryInsertJobOperatorAsync           | 5     |
| 6     | PythonOperator                           | 5     |
| 7     | PostgresOperator                         | 4     |
| 8     | DummyOperator                            | 3     |
| 9     | BashOperator                             | 2     |
| 10    | BigQueryCreateEmptyDatasetOperator       | 2     |
| 11    | BigQueryCreateEmptyTableOperator         | 2     |
| 12    | BigQueryDeleteDatasetOperator            | 2     |
| 13    | BigQueryInsertJobOperator                | 1     |
| 14    | GCSObjectUpdateSensorAsync               | 1     |
| 15    | LocalFilesystemToGCSOperator             | 1     |
| 16    | BigQueryIntervalCheckOperatorAsync       | 1     |
| 17    | BigQueryGetDataOperatorAsync             | 1     |
| 18    | BigQueryCheckOperatorAsync               | 1     |
| 19    | GCSObjectExistenceSensorAsync            | 1     |
| 20    | GCSUploadSessionCompleteSensorAsync      | 1     |
| 21    | BigQueryValueCheckOperatorAsync          | 1     |
| 22    | BigQueryTableExistenceSensorAsync        | 1     |
| 23    | BigQueryTablePartitionExistenceSensor    | 1     |
| 24    | GCSObjectsWithPrefixExistenceSensorAsync | 1     |

**Comment by phanikumv** [comment]
what if I have a custom operator which inherits from another operator like DataprocSubmitJobOperatorAsync?

**Comment by rajaths010494** [comment]
Currently, astrolabe is using the query 
```
SELECT 
  operator,
  SUM(task_success_count),
  SUM(total_task_count) AS total_task_count,
  COUNT(DISTINCT acct_id) AS distinct_customer_count
FROM dwh.reporting.astro_cust_usage_operators_daily
WHERE date >= '2022-01-01'
GROUP BY 1
ORDER BY (total_task_count * distinct_customer_count) DESC
```
to fetch the count.
Currently, astrolabe do not have the ability to observe subclassing/inheritance.

Nebula task data is provided by the deployments’ task_instance table in the metadata DB, which does not provide this information.

Astro task data is provided by task instance splunk logs, which do not provide this information.

Unless telemetry supports the listing of parent classes, presumably via MRO we cannot get this information.

To be possible, for the data team to collect the data and provide insight, it would require either:
Splunk task logs to include the inheritance (for Astro)
Airflow Metadb to include in the task instance tables (for Nebula)

**Comment by rajaths010494** [comment]
If we use dag code to fetch the data then we need to use imports for operators or sensors to get the info
 - there can be unused imports in dags.
 - `from airflow.operators.dummy import DummyOperator as do` 
      which could cause issues and might not get the proper count.
  - There can be a separate python file written for inheritance or subclasses are called and imported inside dag file might not get the needed info for us.
  - Custom operator names used in dag task can be fetched since the task operator which is used is stored in the
     task_instance model.

**Comment by kaxil** [comment]
Did you look at the `data` column in `serialized_dag` table @rajaths010494 -- check if we store the path to the operator in the serialized json.

Separately, did you manage to find a way of identifying whether an operator was async or not?

**Comment by rajaths010494** [comment]
Yes i have checked it table contains operator/sensor and module path 

```
"_task_type": "BigQueryGetDataOperatorAsync",
"_task_module": "astronomer.providers.google.cloud.operators.bigquery",
```
 
I Checked the trigger table where temporarily data is stored when the task has been deferred but it's not persisted once the task is completed.

**Comment by rajaths010494** [comment]
![image.png](https://images.zenhubusercontent.com/61cd5705d341327dd82ca4b5/e90d85bf-e9d8-4b5a-b273-8238db2b4bbe)

**Comment by rajaths010494** [comment]
When async operator/sensor runs in task_instance table column next_kwargs has been updated with null whereas for sync operators /sensors it is empty.
`select operator, count(*) as count from task_instance where next_kwargs is not null group by operator order by count desc;` 


![Screenshot 2022-06-30 at 10.55.43 AM.png](https://images.zenhubusercontent.com/61cd5705d341327dd82ca4b5/1d22af7a-53f0-4c38-9106-2ec3bd5a7389)

empty for sync operators 

`select operator, count(*) as count from task_instance where next_kwargs is null group by operator order by count desc;`

![Screenshot 2022-06-30 at 10.56.51 AM.png](https://images.zenhubusercontent.com/61cd5705d341327dd82ca4b5/8f1363c2-6168-4710-b99a-60860484196d)

**Comment by rajaths010494** [comment]
Documentation of the findings .(WIP)
https://www.notion.so/astronomerio/Approach-to-find-usage-metrics-of-Operators-Sensors-947dd9d9968444fe984ee34ef6c4a420

**Comment by phanikumv** [comment]
Please mention the tabular summary of all the analysis done on this story and the plan ahead.

**Comment by rajaths010494** [comment]
|                                    |Findings                                                                                                                                          |Next steps                                                                          |Notes                                                                                                                                                                                              |
|-------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Check inheritance of custom operator/sensor|Currently, we don’t readily have data available in the airflow DB.                                                                                |Add the inheritance /sub classes details in task_instance table and logs for splunk.|Suggestion add op_classpath similar present in sensor_instance in task_instance also to record where the operator/sensor is coming from.                                                           |
|Check for async operator/sensor            |From the task_instance table and column next_kwargs when a task is deferred value is added so an non empty column means its async operator/sensor |We can get the async operators count                                                |                                                                                                                                                                                                   |
|Check for sync operator/sensor             |so an empty column from the task_instance and next_kwargs an empty value means a tasks was not deferred.                                          |                                                                                    |airflow also has async operators added in the repo. So we can check from the serialised_dag table and data column to get _task_type  and _task_module  to know the class path for more information.|

**Comment by vikramkoka** [comment]
> 

Thanks @phanikumv , will review

**Comment by pankajkoti** [comment]
Spike story is complete. Closing the issue.
