### ISSUE TITLE
Implement OL extractors

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#452]
Implement OL extractors for the below set of async operators:
- [ ] Bigquery
- [ ] Snowflake
- [ ] Databricks
- [ ] Redshift

**Comment by kaxil** [comment]
Should we split this into multiple tasks? @pankajkoti @phanikumv

**Comment by phanikumv** [comment]
yes @kaxil, we are implementing this in a separate issue per each provider.

**Comment by pankajkoti** [comment]
Closing this as we have created separate issues.
