### ISSUE TITLE
Implement Data bricks OL extractors

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#460]
- [x] Need to decide on what are all the lineage data/key facets data which can be covered in extractor.
- [ ] Add extractor for async Data bricks operators
- [ ]  Add unit tests for the custom extractor.

**Comment by bharanidharan14** [comment]
Started working on the Data bricks extractor spike need to decide on what are all the lineage data/key facets data which can be covered in extractor.

**Comment by phanikumv** [comment]
Why would this be a SPIKE, this would rather be an implementation story. Please change the title accordingly

**Comment by bharanidharan14** [comment]
To start with the extractor decided to extract the following details in facets

- Job properties,
- cluster properties,
- user,
- userId,
- job status
- orgId (if available)
- notebook.path,
- job type (if available),
- job id (if available),
- job runId (if available),
- clusterName,
- subscription id (if available)

**Comment by bharanidharan14** [comment]
@pankajkoti 

we have` /2.1/jobs/runs/get` API to get the runs status of job submitted, we can get some more data in this
{
  "job_id": 11223344,
  "run_id": 455644833,
  "number_in_job": 455644833,
  "creator_user_name": "user.name@databricks.com",
  "original_attempt_run_id": 455644833,
  "state": {
    "life_cycle_state": "PENDING",
    "result_state": "SUCCESS",
    "user_cancelled_or_timedout": false,
    "state_message": ""
  },
  "schedule": {
    "quartz_cron_expression": "20 30 * * * ?",
    "timezone_id": "Europe/London",
    "pause_status": "PAUSED"
  },
  "tasks": [
    {
      "run_id": 2112892,
      "task_key": "Orders_Ingest",
      "description": "Ingests order data",
      "job_cluster_key": "auto_scaling_cluster",
      "spark_jar_task": {
        "main_class_name": "com.databricks.OrdersIngest",
        "run_as_repl": true
      },
      "libraries": [
        {
          "jar": "dbfs:/mnt/databricks/OrderIngest.jar"
        }
      ],
      "state": {
        "life_cycle_state": "INTERNAL_ERROR",
        "result_state": "FAILED",
        "state_message": "Library installation failed for library due to user error. Error messages:\n'Manage' permissions are required to install libraries on a cluster",
        "user_cancelled_or_timedout": false
      },
      "run_page_url": "https://my-workspace.cloud.databricks.com/#job/39832/run/20",
      "start_time": 1629989929660,
      "setup_duration": 0,
      "execution_duration": 0,
      "cleanup_duration": 0,
      "end_time": 1629989930171,
      "cluster_instance": {
        "cluster_id": "0923-164208-meows279",
        "spark_context_id": "4348585301701786933"
      },
      "attempt_number": 0
    },
    {
      "run_id": 2112897,
      "task_key": "Match",
      "description": "Matches orders with user sessions",
      "depends_on": [
        {
          "task_key": "Orders_Ingest"
        },
        {
          "task_key": "Sessionize"
        }
      ],
      "new_cluster": {
        "spark_version": "7.3.x-scala2.12",
        "node_type_id": "i3.xlarge",
        "spark_conf": {
          "spark.speculation": true
        },
        "aws_attributes": {
          "availability": "SPOT",
          "zone_id": "us-west-2a"
        },
        "autoscale": {
          "min_workers": 2,
          "max_workers": 16
        }
      },
      "notebook_task": {
        "notebook_path": "/Users/user.name@databricks.com/Match"
      },
      "state": {
        "life_cycle_state": "SKIPPED",
        "state_message": "An upstream task failed.",
        "user_cancelled_or_timedout": false
      },
      "run_page_url": "https://my-workspace.cloud.databricks.com/#job/39832/run/21",
      "start_time": 0,
      "setup_duration": 0,
      "execution_duration": 0,
      "cleanup_duration": 0,
      "end_time": 1629989930238,
      "cluster_instance": {
        "cluster_id": "0923-164208-meows279"
      },
      "attempt_number": 0
    },
    {
      "run_id": 2112902,
      "task_key": "Sessionize",
      "description": "Extracts session data from events",
      "existing_cluster_id": "0923-164208-meows279",
      "spark_jar_task": {
        "main_class_name": "com.databricks.Sessionize",
        "run_as_repl": true
      },
      "libraries": [
        {
          "jar": "dbfs:/mnt/databricks/Sessionize.jar"
        }
      ],
      "state": {
        "life_cycle_state": "INTERNAL_ERROR",
        "result_state": "FAILED",
        "state_message": "Library installation failed for library due to user error. Error messages:\n'Manage' permissions are required to install libraries on a cluster",
        "user_cancelled_or_timedout": false
      },
      "run_page_url": "https://my-workspace.cloud.databricks.com/#job/39832/run/22",
      "start_time": 1629989929668,
      "setup_duration": 0,
      "execution_duration": 0,
      "cleanup_duration": 0,
      "end_time": 1629989930144,
      "cluster_instance": {
        "cluster_id": "0923-164208-meows279",
        "spark_context_id": "4348585301701786933"
      },
      "attempt_number": 0
    }
  ],
  "job_clusters": [
    {
      "job_cluster_key": "auto_scaling_cluster",
      "new_cluster": {
        "spark_version": "7.3.x-scala2.12",
        "node_type_id": "i3.xlarge",
        "spark_conf": {
          "spark.speculation": true
        },
        "aws_attributes": {
          "availability": "SPOT",
          "zone_id": "us-west-2a"
        },
        "autoscale": {
          "min_workers": 2,
          "max_workers": 16
        }
      }
    }
  ],
  "cluster_spec": {
    "existing_cluster_id": "0923-164208-meows279",
    "new_cluster": {
      "num_workers": 0,
      "autoscale": {
        "min_workers": 0,
        "max_workers": 0
      },
      "spark_version": "string",
      "spark_conf": {},
      "aws_attributes": {
        "first_on_demand": 0,
        "availability": "SPOT",
        "zone_id": "string",
        "instance_profile_arn": "string",
        "spot_bid_price_percent": 0,
        "ebs_volume_type": "GENERAL_PURPOSE_SSD",
        "ebs_volume_count": 0,
        "ebs_volume_size": 0,
        "ebs_volume_iops": 0,
        "ebs_volume_throughput": 0
      },
      "node_type_id": "string",
      "driver_node_type_id": "string",
      "ssh_public_keys": [
        "string"
      ],
      "custom_tags": {
        "property1": "string",
        "property2": "string"
      },
      "cluster_log_conf": {
        "dbfs": {
          "destination": "string"
        },
        "s3": {
          "destination": "string",
          "region": "string",
          "endpoint": "string",
          "enable_encryption": true,
          "encryption_type": "string",
          "kms_key": "string",
          "canned_acl": "string"
        }
      },
      "init_scripts": [
        {
          "dbfs": {
            "destination": "string"
          },
          "file": {
            "destination": "string"
          },
          "S3": {
            "destination": "string",
            "region": "string",
            "endpoint": "string",
            "enable_encryption": true,
            "encryption_type": "string",
            "kms_key": "string",
            "canned_acl": "string"
          }
        }
      ],
      "spark_env_vars": {},
      "enable_elastic_disk": true,
      "driver_instance_pool_id": "string",
      "instance_pool_id": "string",
      "policy_id": "string"
    },
    "libraries": [
      {
        "jar": "dbfs:/my-jar.jar",
        "egg": "dbfs:/my/egg",
        "whl": "dbfs:/my/whl",
        "pypi": {
          "package": "simplejson==3.8.0",
          "repo": "https://my-repo.com"
        },
        "maven": {
          "coordinates": "org.jsoup:jsoup:1.7.2",
          "repo": "https://my-repo.com",
          "exclusions": [
            "slf4j:slf4j",
            "*:hadoop-client"
          ]
        },
        "cran": {
          "package": "geojson",
          "repo": "https://my-repo.com"
        }
      }
    ]
  },
  "cluster_instance": {
    "cluster_id": "0923-164208-meows279",
    "spark_context_id": "string"
  },
  "git_source": null,
  "overriding_parameters": {
    "jar_params": [
      "john",
      "doe",
      "35"
    ],
    "notebook_params": {
      "name": "john doe",
      "age": "35"
    },
    "python_params": [
      "john doe",
      "35"
    ],
    "spark_submit_params": [
      "--class",
      "org.apache.spark.examples.SparkPi"
    ],
    "python_named_params": {
      "name": "task",
      "data": "dbfs:/path/to/data.json"
    }
  },
  "start_time": 1625060460483,
  "setup_duration": 0,
  "execution_duration": 0,
  "cleanup_duration": 0,
  "end_time": 1625060863413,
  "trigger": "PERIODIC",
  "run_name": "A multitask job run",
  "run_page_url": "https://my-workspace.cloud.databricks.com/#job/11223344/run/123",
  "run_type": "JOB_RUN",
  "attempt_number": 0,
  "repair_history": [
    {
      "type": "ORIGINAL",
      "start_time": 1625060460483,
      "end_time": 1625060863413,
      "state": {
        "life_cycle_state": "PENDING",
        "result_state": "SUCCESS",
        "user_cancelled_or_timedout": false,
        "state_message": ""
      },
      "id": 734650698524280,
      "task_run_ids": [
        1106460542112844,
        988297789683452
      ]
    }
  ]
}

**Comment by phanikumv** [comment]
Please mention the discussion points with Ross and conclude on this.

**Comment by bharanidharan14** [comment]
The purpose of adding Databricks extractor in Airflow is to emit the lineage data of Databricks jobs triggered from Airflow by `DatabricksSubmitRunOperatorAsync` and `DatabricksRunNowOperatorAsync` operators.

For the extraction, To start with some basic details found some Databricks API `/2.1/jobs/runs/get` , this API provides us only the run and job details and couldn't find anything around the input and output log, going forward with this details got a chance to connect with @rossturk  and Maciej and discussed what can be extracted more for the lineage log on the databricks jobs. Based on the discussion with them, the existing [openlineage/spark integration](https://openlineage.io/integration/apache-spark/) would work in this case and it will know what the job does, so the openlineage/spark integration should be used to emit lineage from those jobs

@rossturk  can you please confirm this and add your comments

cc: @pankajkoti

**Comment by rossturk** [comment]
I agree - if the goal is to extract data lineage from Spark jobs, the direct integration between OpenLineage and Spark should be used. This is the way to get input/output metadata from Spark - Airflow does not yet have a mechanism for observing what goes on inside Spark.

There may still be work we can do to ease the configuration of the OL/Spark integration - perhaps we can have the operator inject the SparkListener configuration and `OPENLINEAGE_URL` / `OPENLINEAGE_API_KEY` values as it submits the job?

**Comment by bharanidharan14** [comment]
@rossturk whats your thought on implementing this OL extractor ? Do we need this Databricks OL Extractor ?

**Comment by bharanidharan14** [comment]
Based on the conversation with @rossturk, its up to us to decide whether to have extractor, If we have it will be like additional information but it won’t capture lineage.

**Comment by pankajkoti** [comment]
Since the lineage information can be extracted post enabling lineage in Databricks, and we can only derive the metadata information regarding the job like jobID, jobName, etc. we're concluding that we're not going to build an extractor for Databricks at the moment. Also, closing the issue.

cc: @kaxil
