### ISSUE TITLE
Azure DataFactory DAG is  failing in run_pipeline_wait

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astronomer-providers#461]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/microsoft/azure/operators/data_factory.py", line 86, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: The pipeline run 8680702e-f1ed-11ec-8961-6e35464960d1 has Failed.

**Comment by rajaths010494** [comment]
An storage account was deleted which has been created and connection string  for the storage account has been updated in astro cloud.

**Comment by pankajkoti** [comment]
Thank you @rajaths010494 for looking into this and fixing it

**Comment by phanikumv** [comment]
Ran fine today.Hence closing.
