### ISSUE TITLE
Implement OpenLineage extractor for Redshift async operators

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#462]
Implement OpenLineage extractor for Redshift async operators

- [x] RedshiftSQLOperatorAsync
- [x] RedshiftDataOperatorAsync

**Comment by rajaths010494** [comment]
Broken plugin: [openlineage.airflow.plugin] Failed to import astronomer.providers.amazon.aws.extractors.redshift.RedshiftAsyncExtractor . 
Update OL version to 0.10.0 and 0.11.0 and tried the same issue exists.
Connect with @pankajkoti and try to resolve this.

**Comment by pankajkoti** [comment]
Current issue is that with the latest Astro image and recent OpenLineage releases 0.9.0, 0.10.0 & 0.11.0 the plugin load is failing for Redshift Extractor. @rajaths010494 to connect with Maciej (GetInData team) and dig deeper into resolving this issue today.

**Comment by rajaths010494** [comment]
Waiting for PR to be raised from Ol side so that i can review and implement the same in our extractor

**Comment by pankajkoti** [comment]
We can refer to this page: https://www.notion.so/astronomerio/Developing-OpenLineage-in-Astro-9f30a74c74354f168279c1205f4d89a6 to install local packages

**Comment by rajaths010494** [comment]
Today have a connect with maciej for broken plugin issue.

**Comment by rajaths010494** [comment]
Draft PR has been raised https://github.com/astronomer/astronomer-providers/pull/561

**Comment by rajaths010494** [comment]
Test cases are pending

**Comment by bharanidharan14** [comment]
Expected to be completed EOD

**Comment by rajaths010494** [comment]
New version of `openlineage-airflow==0.12.0` has been released, will revamp unwanted code and then push the changes

**Comment by rajaths010494** [comment]
Have incorporated the new ``openlineage-airflow==0.12.0`` code for redhsift extractors.

**Comment by rajaths010494** [comment]
Ready for review and i have rebased
