### ISSUE TITLE
Create documentation for connectivity to Azure Blob

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#465]

**Comment by bharanidharan14** [comment]
Added documentation on Azure storage blob connection creation

Notion Page Documentation link: [Azure Blob Connection Creation(wasb)](https://www.notion.so/astronomerio/Azure-Blob-Connection-Creation-wasb-30983534d0104625b607ec3bb4dbe637)

**Comment by phanikumv** [comment]
Have given review comments which need to be addressed before moving to Done state.

**Comment by bharanidharan14** [comment]
Addressed Review comments
