### ISSUE TITLE
Automate testing RC version of providers

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#472]
Whenever a RC(release candidate) is created on Airflow OSS which includes an upgrade of any of the providers, we would like to have some automation to test the providers from the RC with the astronomer-providers build to check that our async operators are not impacted if there's some breaking change.
If we observe some breaking change, we can quickly prioritise on making the necessary changes on astronomer-providers implementation so that our customers are not impacted.

We have drafted a [document](https://docs.google.com/document/d/1wVRxELmQmmyCzNocd2LARrN8683MuvR8CbUbb8uOOl4/edit?usp=sharing) on the ideation for implementation after initial brainstorming between @phanikumv and @pankajkoti 

Tasks:
- [x] Test https://github.com/apache/airflow/issues/24806 RC 2.3.3rc1 to get familiarised with the effort
- [x] Add task in master DAG to list python script
- [x] Write script to update setup.cfg with provider releases
- [x] Build make target to accept arguments for running the script to update setup.cfg and then build image + deploy to astro cloud existing deployment of Integration Tests since we cannot copy connections from one deployment to another at the moment in Astro Cloud and will be tedious to create connections in a new deployment using some script (also includes complexities like storing connection secrets secure)

**Comment by pankajkoti** [comment]
Added a make target accepting pinned provider versions to replace dependencies in the setup.cfg.

Working next on building an image with the updated setup.cfg and deploying to Astro Cloud Integration Tests deployment and triggering the master DAG.
