### ISSUE TITLE
azure key vault integration prefixes variables_prefix and connections_prefix incorrectly

### ISSUE THREAD

**Issue by rob-1126** [astronomer/astronomer-providers#485]
**Describe the bug**
azure key vault adds a - between the key prefix and the secret name when it reads it from azure key vault. It does this even when the key prefix is "" so secrets end up named -my-secret instead of my-secret.

**To Reproduce**
Follow the instructions to set up an azure key vault integrated install with a connections_prefix of "".
Create a secret named -my-var in azure key vault.
Use the example dag provided in the docs with Variable.get("my-var")
You will see that it fetches the variable because it is incorrectly mapping my-var to -my-var instead of my-var.

**Expected Behavior**
connections_prefix and variables_prefix dont add a leading - when they are set to "". 

**Additional context**
From my understanding null his historically not been supported as a value for that even though its passed as a JSON blob? Might be more idiomatic but if this is changed I'd think all providers should be changed. I suggest we don't do it and just continue to use "" but fix our prefixing as described in this ticket.

**Comment by rob-1126** [comment]
Doc fix filed at https://github.com/astronomer/issues/issues/4796 intentionally updates docs to match the current (pre-fix) behavior of this provider. Once this ticket is done, the docs should be updated again to state the behavior changes with Airflow v. <fix version>.

**Comment by rajaths010494** [comment]
Secrets are used in OSS airflow and providers don't have that. So this would be a fix in OSS.

**Comment by rajaths010494** [comment]
Hi @rob-1126 Separator used to concatenate path_prefix and secret_id so when you make path_prefix="" it will take it empty string and add separator and then secret_id.
ex ` -my-var` so if ur secret_id itself is -my-var the end key would be ` --my-var`..
https://github.com/apache/airflow/discussions/22150

**Comment by rajaths010494** [comment]
https://github.com/apache/airflow/pull/26749

**Comment by rajaths010494** [comment]
PR is approved and waiting for it to be merged.

**Comment by rajaths010494** [comment]
PR got merged in OSS airflow
