### ISSUE TITLE
Understand & Investigate AIP-48

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#497]
Understand what AIP-48 covers

https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-48+Data+Dependency+Management+and+Data+Driven+Scheduling

**Comment by bharanidharan14** [comment]
Going through the Documentation

**Comment by bharanidharan14** [comment]
Tech Talk on August 9th 2022

**Comment by pankajkoti** [comment]
Understanding is complete by Bharani.  Closing the issue and we will have a tech talk on 9th August for team knowledge sharing.
