### ISSUE TITLE
Enhance Sphinx extension for Operators & Sensors listing

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#508]
The current implementation in PR https://github.com/astronomer/astronomer-providers/pull/504 lists the Operators and Sensors using raw HTML.
As an enhancement to this, check how we can use the `list-table `Sphinx directive to dynamically generate table rows so that we can reference the Sphinx Class definitions, include python code and add references to other needed Sphinx directives like the corresponding example DAGs for the operators & sensors

**Comment by phanikumv** [comment]
Stale request
