### ISSUE TITLE
Build ExternalDeploymentTaskSensor

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#576]
Relevant link : https://astronomer.slack.com/archives/C0387PMM2E7/p1659556447204159

**Comment by bharanidharan14** [comment]
Based on the slack conversation, @pohek321 tried using the `HttpSensorAsync` and pass the `response_check` lambda function to check for the state he expected to behave as async task, In HttpSensorAsync if we pass `response_check`, it behaves as sync version of HTTP sensor. 
So this `ExternalDeploymentTaskSensor` task is to check for the upstream deployment task is in completed state, waits until the task is "running" and mark the task as failed if the task is not in "success" state.

**Comment by bharanidharan14** [comment]
Completed Dev code part, writing test case
