### ISSUE TITLE
Make run-mypy not taking image name

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astronomer-providers#578]
**Describe the bug**
When i run the make run-mypy command its not building and running mypy command.

**To Reproduce**
make run-mypy

**Expected behavior**
It is supposed to create an image and run mypy command successfully.

**Screenshots**
<img width="663" alt="Screenshot 2022-08-09 at 11 56 06 AM" src="https://user-images.githubusercontent.com/92459020/183585507-928e0a19-7abc-4ac2-9a2d-c3e9654f64a3.png">

**Comment by pankajkoti** [comment]
@rajaths010494 are you working on this, should be a quick fix. I believe I missed adding that earlier to this `make` target while working on this PR: https://github.com/astronomer/astronomer-providers/pull/509. The change should be similar to other `make` targets in the PR; we need to pass the `IMAGE_NAME` build-arg to the command in the `make` target.

**Comment by rajaths010494** [comment]
Yes i am raising an PR in 5mins.
