### ISSUE TITLE
Use poke_interval instead of poll_interval

### ISSUE THREAD

**Issue by m1racoli** [astronomer/astronomer-providers#613]
**Is your feature request related to a problem?**

Airflow sensors by default (inherited from `BaseSensorOperator`) have an attribute *poke_interval*, which controls the frequency of how often to poke a particular resource while waiting to complete.

I've noticed that many implementations of async sensors in the Astronomer providers do not adhere to this specification and instead introduced a new attribute *poll_interval* with an almost identical meaning.

**Describe the solution you'd like**

All airflow sensors (sync or async) should only have one attribute controlling the poke frequency, which is *poke_interval*.

Furthermore for the sake of consistency this attribute should also be adopted by async operators.

**Describe alternatives you've considered**

The alternative would be *poll_interval* for all sensors, which seems to be a breaking change.

**Additional context**

Nope

**Comment by kaxil** [comment]
cc @pankajastro @rajaths010494 @bharanidharan14 @phanikumv

**Comment by bharanidharan14** [comment]
Use `poke_interval` instead of `poll_interval` for all the sensor and fix this for test case

**Comment by bharanidharan14** [comment]
Most of the sensor inherits from BaseSensorOperator 
![Screenshot 2022-09-16 at 3.48.12 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/fc8ac735-16cd-4d84-b81c-73447d817af2
)

**Comment by m1racoli** [comment]
Thanks a lot, everyone!
