### ISSUE TITLE
Run a single unit test in container

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#627]
Currently, `make run-tests` run all unit tests it would be great if we can run a single test

**Comment by kaxil** [comment]
Currently, you can do it by running the following:

```
make shell
```

and then:

```
cd /usr/local/airflow/astronomer_providers 
pytest test/.../path_to_file.py
```

**Comment by pankajastro** [comment]
> Currently, you can do it by running the following:
> 
> ```
> make shell
> ```
> 
> and then:
> 
> ```
> cd /usr/local/airflow/astronomer_providers 
> pytest test/.../path_to_file.py
> ```

This looks fine to me and this requested feature does not require closing it.
