### ISSUE TITLE
SFTP Async Sensor

### ISSUE THREAD

**Issue by tseruga** [astronomer/astronomer-providers#629]
**Describe the solution you'd like**
Async version of the SFTP sensor now that smart sensors are planned to be removed in 2.4.0.

Ability to watch a path on an SFTP server and complete when a file pattern is matched at the path.

----

I'm currently writing this for internal use at my company following the patterns used in other async sensors in this repo. I plan to contribute this once completed. The sensor is functional, and I'm currently working on the test suite for it.

**Comment by kaxil** [comment]
We are looking forward for you contribution @tseruga
