### ISSUE TITLE
Parameterize example DAGs for integration tests

### ISSUE THREAD

**Issue by kaxil** [astronomer/astronomer-providers#63]
We want to run all the example DAGs in this repo on a weekly basis at least to start with (we can change frequency later on).

There is also a recent related AIP worth reading and adding your thoughts on it - https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-47+New+design+of+Airflow+System+Tests

**Acceptance Criteria**:
- [x] All the example DAGs in this repo should be updated so the parameters / env related values come from Environment Variables like [google provider](https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py) but not like [Snowflake Provider](https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/snowflake/example_dags/example_snowflake.py). Here Snowflake example needs to be corrected.
- [ ] Have one of the following that pushes all the example DAG in Gen2 cloud deployment, creates necessary connections and runs all the DAGs. And send a Slack message with the summary of the run :
   -  (a) **Scheduled CI job**
   - (b) A master DAG that runs on a schedule in the same deployment - #124 addresses this point

**Note**: The DAG should contain cleanup tasks at the end to destroy all the resources, example nuking the BigQuery table as the last step.

**Comment by phanikumv** [comment]
@pankajastro - please regularly post updates here on the progress being made.

**Comment by pankajastro** [comment]
Building image -> Mostly done but currently using pip install to install provider code in image 
Basic working script to push/deploy dag in cloud env -> Done
Master DAG to trigger example DAG -> In progress

**Comment by pankajastro** [comment]
Update
--------
Updating example code -> Done
Building image -> Done
Script to push/deploy dag in cloud env -> Done
Master DAG to trigger example DAG -> Done
Testing -> I have scheduled it for smaller schedule_interval and watching the behaviour 
Report Generation -> TODO

**Comment by phanikumv** [comment]
Created #124 to address the below point:-

Have one of the following that pushes all the example DAG in Gen2 cloud deployment, creates necessary connections and runs all the DAGs. And send a Slack message with the summary of the run :
   -  (a) **Scheduled CI job**
   - (b) A master DAG that runs on a schedule in the same deployment

**Comment by phanikumv** [comment]
@pankajastro - please confirm whether point 1 in the acceptance criteria is addressed so that we can close the story.If so, please update the ticket accordingly.

**Comment by pankajastro** [comment]
Parameterizion of example dag has done. 
PR: https://github.com/astronomer/astronomer-providers/pull/102
