### ISSUE TITLE
Use poke_interval for operators

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#641]
To Maintain consistency on the `poll_interval` parameter name for operator, somewhere it is polling_interval, poll_interval, So instead of `poll_interval` use `poke_interval` for operator as well

**Comment by bharanidharan14** [comment]
Few of Operator uses `poll_interval` from its parent class which is OSS sync operator, we can change the internal occurrence

**Comment by bharanidharan14** [comment]
Attaching the operator list 

![Screenshot 2022-09-16 at 3.46.48 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/67c91e1c-c1b4-421e-8070-85d77560d0b6)

**Comment by phanikumv** [comment]
Make this change post doing the corresponding change on OSS side
