### ISSUE TITLE
Implement changes in async operators/sensors made in OSS

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#644]
Find List of operators/sensors which need changes compared to OSS operator/sensors and implement those changes.

**Comment by rajaths010494** [comment]
Kubernetes - cleanup remote pods
SFTP - filepath not being used.

**Comment by phanikumv** [comment]
Can we create separate issues for each operator identified above? @rajaths010494

**Comment by pankajastro** [comment]
since we have contributed these operators to OSS. This is not a valid request
