### ISSUE TITLE
Add integration tests to Dbt Async Operators

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#656]
**Is your feature request related to a problem? Please describe.**
Need to add integration tests to Dbt Async Operators and Sensors. 
This is a follow up to https://github.com/astronomer/astronomer-providers/pull/623

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajastro** [comment]
@rajaths010494 PR https://github.com/astronomer/astronomer-providers/pull/889 should handle it, right?

**Comment by phanikumv** [comment]
Closing as the issue is addressed in #889
