### ISSUE TITLE
Implement remaining S3 Sensors / Operators

### ISSUE THREAD

**Issue by kaxil** [astronomer/astronomer-providers#66]
As a follow-up to https://github.com/astronomer/astronomer-providers/issues/14 we should complete the remaining operators/sensors in the s3 module for the Amazon provider. Please look at [docs](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/) to see if there are other operators we should make Async (**Principle** - Only create Async operators for the “sync-version” of operators that do some level of polling; take more than a few seconds to complete). 

- [ ] `S3CopyObjectOperator` @phanikumv 
- [ ] `S3FileTransformOperator` @sunank200
- [x] [`S3KeySizeSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/sensors/s3/index.html#airflow.providers.amazon.aws.sensors.s3.S3KeySizeSensor) @sunank200 
- [x] [`S3KeysUnchangedSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/sensors/s3/index.html#airflow.providers.amazon.aws.sensors.s3.S3KeysUnchangedSensor) @sunank200 
- [x] [`S3PrefixSensor`](https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/_api/airflow/providers/amazon/aws/sensors/s3/index.html#airflow.providers.amazon.aws.sensors.s3.S3PrefixSensor) @phanikumv 

**Acceptance Criteria**:
- [ ] Unit Tests coverage in the PR (80% Code Coverage -- We will need to add CodeCov separately to measure code cov) with all of them passing 
- [ ] Example DAG using the async Operator that can be used to run Integration tests that are parametrized via Environment variables. Example - https://github.com/apache/airflow/blob/8a03a505e1df0f9de276038c5509135ac569a667/airflow/providers/google/cloud/example_dags/example_bigquery_to_gcs.py#L33-L35
- [ ] Add proper docstrings for each of the methods and functions including Example DAG on how it should be used (populate 
- [ ] Exception Handling in case of errors 
- [ ] Improve the OSS Docs to make sure it covers the following:
   - [ ] Has an example DAG for the sync version
   - [ ] How to add a connection via Environment Variable & explain each of the fields. Example - https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/connections/postgres.html
   - [ ] How to use Guide for the Operator - example: https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html

**Comment by phanikumv** [comment]
S3CopyObjectOperator - This Operator executes a copy_object method which creates a copy of an object that is already stored in S3. No process id generated when we execute a copy_object method.

**Comment by sunank200** [comment]
`S3FileTransformOperator` uses `check_for_key`, `get_key` and `select_key` for which there is no process-id being returned. Also, `aiobotocore` and `botocore` doesn't return process-id either. The hook methods implemented on OSS side also would be blocking call.

My understanding is that async implementation for this operator would not work.

Please correct me of I am wrong.

**Comment by sunank200** [comment]
`S3FileTransformOperator` uses `check_for_key`, `get_key` and `select_key` for which there is no process-id being returned. Also, `aiobotocore` and `botocore` doesn't return process-id either. The hook methods implemented on OSS side also would be blocking call.

My understanding is that async implementation for this operator would not work.

Please correct me of I am wrong.

**Comment by sunank200** [comment]
`S3FileTransformOperator` uses `check_for_key`, `get_key` and `select_key` for which there is no process-id being returned. Also, `aiobotocore` and `botocore` doesn't return process-id either. The hook methods implemented on OSS side also would be blocking call.

My understanding is that async implementation for this operator would not work.

Please correct me of I am wrong.

**Comment by phanikumv** [comment]
PR https://github.com/astronomer/astronomer-providers/pull/91 will add the S3PrefixSensor
