### ISSUE TITLE
Several dead links in the docs

### ISSUE THREAD

**Issue by BasPH** [astronomer/astronomer-providers#661]
**Describe the bug**
Several links in this list (https://astronomer-providers.readthedocs.io/en/stable/providers/index.html) give me a 404:

![image](https://user-images.githubusercontent.com/6249654/191791013-7c517c8a-4863-456f-afcd-feaa39db66f5.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kaxil** [comment]
Yeah, the ones for Microsoft and Snowflake are broken.
