### ISSUE TITLE
`make docs` dev command failed on main branch

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#664]
**Describe the bug**
Recently I'm facing an issue while running `make docs` in my env. may be related to https://github.com/executablebooks/sphinx-copybutton/issues/170 issue but not sure

**To Reproduce**
run `make docs` in astronomer-providers

<img width="1350" alt="Screenshot 2022-09-24 at 12 38 31 AM" src="https://user-images.githubusercontent.com/98807258/192040465-d23e8fd6-71c3-49da-bd7b-3572ed6d45cf.png">

**Comment by kaxil** [comment]
Did you build the image from scratch?

The following library should be installed
https://github.com/astronomer/astronomer-providers/blob/3b41eb70b14104b1a57a85c413edb708fa7d2359/setup.cfg#L81

**Comment by pankajastro** [comment]
> Did you build the image from scratch?
> 
> The following library should be installed
> 
> https://github.com/astronomer/astronomer-providers/blob/3b41eb70b14104b1a57a85c413edb708fa7d2359/setup.cfg#L81

hmm, After your comments, I build it from scratch with
```
make stop
make clean
docker system prune -a
make build-run
```
but the issue persists. I was trying this from pychram terminal in conda env but after manually installing `sphinx-copybutton` in env with `conda install -c conda-forge sphinx-copybutton` it started working

**Comment by kaxil** [comment]
Looks like it is because the `make docs` command does not currently use docker.. may be run `pip install -e .[docs]` in that?

https://github.com/astronomer/astronomer-providers/blob/3b41eb70b14104b1a57a85c413edb708fa7d2359/Makefile#L45-L46

**Comment by pankajastro** [comment]
running
```
pip install -e .[docs]
```
and then `make docs` worked!
