### ISSUE TITLE
Mypy and tests are failing for new RC providers prepared on 28th September, 2022

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#678]
We've automated creating a PR upon changing the `setup.cfg` with `make test-rc-deps` target. However we're observing few `mypy` failures and tests failure that can be seen in the PR: https://github.com/astronomer/astronomer-providers/pull/673

We need to fix the failures observed in the checks for the above PR.

**Comment by rajaths010494** [comment]
this is same as https://app.zenhub.com/workspaces/airflow-providers-team-61a89ee7fbf048001dc8378d/issues/astronomer/astronomer-providers/702
