### ISSUE TITLE
Mypy and tests failures for Google provider 8.4.0rc2

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#702]
We deployed the Google provider 8.4.0rc2 on our team Astro Cloud deployment. DAGs seem to run fine but we're observing few mypy and tests failures. The failures can be observed in the checks on PR: https://github.com/astronomer/astronomer-providers/pull/701

**Comment by rajaths010494** [comment]
As soon as  the stable version of new providers is released will fix this mypy and unit test
