### ISSUE TITLE
Slack and Teams `on_x_callbacks`

### ISSUE THREAD

**Issue by fritz-astronomer** [astronomer/astronomer-providers#709]
**Is your feature request related to a problem? Please describe.**
Airflow users often want to either alert for DAG or Task success or failure. Examples for this are plentiful but still require a lot of "roll it yourself"

**Describe the solution you'd like**
I would like to advise something like
```
import providers.alerts.slack_notification
```
```
with DAG(
  on_failure_callback=slack_notification(channel="xyz", conn_id="abc")
):
```
or 
```
BashOperator(
  ...,
  on_failure_callback=slack_notification(channel="xyz", conn_id="abc")
)
```
with sensible defaults and simple (enough) setup. 
Being able to pass in a message is a bonus. 
Having a default message that gives links to the task, maybe lineage, and failure task logs would be best.

**Comment by pankajastro** [comment]
on_failure_callback expect python callable (i.e python function) what about directly calling using the slack operator in the on_failure_callback callable function?

```
def slack_notification(...)
    SlackWebhookOperator(...).execute(context=None)

with DAG(
  on_failure_callback=slack_notification
):
```

or expectation is to have some function wrapper over these notification operators?

**Comment by fritz-astronomer** [comment]
@pankajastro - I imagine the function signature would be `slack_notification(channel: str, conn_id: str) -> Callable[Context]` - so takes some configuration and returns the callable

**Comment by pankajastro** [comment]
@fritz-astronomer Since Airflow has a notifier feature does it still relevant?
https://airflow.apache.org/docs/apache-airflow/2.6.0/howto/notifications.html#using-a-notifier
https://github.com/apache/airflow/tree/main/airflow/providers/slack/notifications

**Comment by fritz-astronomer** [comment]
No :/ not really. Airflow does need a teams notifier though :)

**Comment by pankajastro** [comment]
We introduced apprise notifier  https://github.com/apache/airflow/pull/31533 that should handle ms team.

**Comment by pankajastro** [comment]
closing this in favour of the Airflow notifier feature.
