### ISSUE TITLE
custom function check_fn passed to S3KeyTrigger is not executed

### ISSUE THREAD

**Issue by maa2m** [astronomer/astronomer-providers#724]
check_fn if not None is not executed to S3KeyTrigger

                        if self.check_fn is None:
                            yield TriggerEvent({"status": "success"})
                        s3_objects = await hook.get_files(
                            client, self.bucket_name, self.bucket_key, self.wildcard_match
                        )
                        yield TriggerEvent({"status": "success", "s3_objects": s3_objects})

**Comment by phanikumv** [comment]
Thank you @maa2m for creating this issue. We will look into this and provide an update soon.

**Comment by bharanidharan14** [comment]
@maa2m Custom function passed to the trigger won't be in executable because it is serialised it will be string
