### ISSUE TITLE
Token error with Sagemaker Async Operators

### ISSUE THREAD

**Issue by fhoda** [astronomer/astronomer-providers#725]
**Describe the bug**
Getting errors with the new Sagemaker Async Operators that I don't get with the traditional ones. I'm using a personal Access Key, Secret, and Session Token as I did with the non async operators for auth.

```
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the DescribeTrainingJob operation: The security token included in the request is invalid.
```

**To Reproduce**
Use the SageMaker async operators with user Access Key, Secret, and Session Token

**Expected behavior**
Expect it to not have auth/token errors.

**Additional context**
When I switch back to the traditional operators in the same dag with the same auth creds it works fine.

@kentdanas also had similar issues and her auth was setup a little different.

**Comment by bharanidharan14** [comment]
The issue is with the session token is not considered while the secrete and access key is given in the connection proper field, not in the extra config
