### ISSUE TITLE
Providers Tests Results Integration with Tesults

### ISSUE THREAD

**Issue by vatsrahul1001** [astronomer/astronomer-providers#731]
**Is your feature request related to a problem? Please describe.**
We are in a Process of creating a QA Dashboard which will display results for all QA tests and also for Providers and Astro-SDK, To implement this we are pushing results  to tesults and the same needs to be done for providers and Astro-SDK as well.

**Describe the solution you'd like**
Integration to tesults is very simple and can be done for various test frameworks. The below steps can be used for [pytest](https://www.tesults.com/docs/pytest)

1. pip install tesults
2. pip install pytest-tesults
3. Create a Tesults Target, This is a target where pytest results will be pushed to tesults
     a) I have already created a tesults target with the name **Astronomer-providers** and target token as "xxxxxx"
4. Now we can use this target token in our pytest command 
    a) **pytest --tesults-target <target Token>**

@phanikumv

**Comment by pankajastro** [comment]
@vatsrahul1001 this has been already done, no?

**Comment by vatsrahul1001** [comment]
yes @pankajastro this is done
