### ISSUE TITLE
[SPIKE/RESEARCH]:Fivetran Providers

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#735]
**Is your feature request related to a problem? Please describe.**
Analyze Fivetran and come up with the list of operators that we can create

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rajaths010494** [comment]
Documentation of Fivetran providers is found [here](https://www.notion.so/astronomerio/Fivetran-3bd9ecfbdcae411faa49cb38595a4571)
