### ISSUE TITLE
Donate `KubernetesPodOperatorAsync` to OSS

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#748]
**Is your feature request related to a problem? Please describe.**
Donate `KubernetesPodOperatorAsync` to OSS

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raphaelauv** [comment]
https://github.com/apache/airflow/pull/29017 ?

**Comment by pankajastro** [comment]
> [apache/airflow#29017](https://github.com/apache/airflow/pull/29017) ?

and https://github.com/apache/airflow/pull/27758. closing it.
