### ISSUE TITLE
DBT operators

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#754]
One of our customer pointed out that they are using dbt-core using [this package](https://github.com/tomasfarias/airflow-dbt-python), which provides DBT Operators. Anyone has any thoughts about this? Would it be something that we can include in our providers package ?

**Comment by phanikumv** [comment]
suggest to use cosmos

**Comment by pankajastro** [comment]
@phanikumv do you have a plan to take this forward or investigate further?

**Comment by phanikumv** [comment]
no cosmos should handle it
