### ISSUE TITLE
Review and add `SqlSensorAsync`

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#755]
Refer to https://astronomer.slack.com/archives/C0387PMM2E7/p1666735714346379
for discussion on `SqlSensorAsync`

_I have a working deferrable sql sensor that works and would like someone to review: https://github.com/astronomer/dev-snowflake-sensor_

**Comment by pankajastro** [comment]
duplicate of https://github.com/astronomer/astronomer-providers/issues/420
