### ISSUE TITLE
SagemakerProcessingOperatorAsync to honor existing_jobs_found

### ISSUE THREAD

**Issue by rajaths010494** [astronomer/astronomer-providers#757]
**Is your feature request related to a problem? Please describe.**
Currently, we are failing if the job already exists in SageMaker

**Describe the solution you'd like**
https://github.com/apache/airflow/pull/27456. The same has been fixed in OSS airflow

**Comment by pankajkoti** [comment]
We're waiting for the SageMaker OSS Airflow PRs with the deferrable parameters to be merged and available in the upcoming release. Post that we will inherit the OSS operator here so that we do not have to do double work.

**Comment by pankajkoti** [comment]
PR #1169 was created and is waiting for reviews.

**Comment by pankajkoti** [comment]
Reverting PR #1169 into PR https://github.com/astronomer/astronomer-providers/pull/1175 as we need a major bump of astronomer-providers as per discussion with the team and tagging this issue to milestone `2.0.0`

**Comment by pankajastro** [comment]
@phanikumv do we still want to add this feature? asking since we have already donated this to OSS and the OSS operator take care of this.

**Comment by phanikumv** [comment]
Closing as the functionality as available in OSS airflow
