### ISSUE TITLE
Add support for private key connection in SFTP Async operator

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#760]
Currently async version doesn't support for the `Private key ` args via connection extra it supports only `key_file` options to connect to SFTP

**Comment by erdos2n** [comment]
@bharanidharan14 can I take this one?

**Comment by bharanidharan14** [comment]
@erdos2n yeah sure, Thanks

**Comment by bharanidharan14** [comment]
@erdos2n Addressed this issue now please take a look at this PR https://github.com/astronomer/astronomer-providers/pull/749

**Comment by rajaths010494** [comment]
Closed as part of PR https://github.com/astronomer/astronomer-providers/pull/749
