### ISSUE TITLE
support assuming roles in async AWS provider using aiobotocore

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#786]
slack thread: https://astronomer.slack.com/archives/C0387PMM2E7/p1669319507283849

**Comment by kaxil** [comment]
Why was this reopened? Is work pending on this?

**Comment by bharanidharan14** [comment]
It was closed as part of this PR https://github.com/astronomer/astronomer-providers/pull/804, May be I moved the status manually to done so it got reopened
