### ISSUE TITLE
[SPIKE/RESEARCH]: Async operators/sensors for AWS EmrServerless API

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#789]
**Is your feature request related to a problem? Please describe.**
Go through the OSS operators for AWS EmrServerless API and find whether it returns a unique job id , using which an async operator/sensor can be built. The outcome of this spike would be to finalize the list of async operators/sensors which can built for AWS EmrServerless.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajastro** [comment]
We have deferrable for in OSS EmrServerlessDeleteApplicationOperator, EmrServerlessCreateApplicationOperator, EmrServerlessStartJobOperator, EmrServerlessStopApplicationOperator

**Comment by phanikumv** [comment]
Closing as the functionality as available in OSS airflow
