### ISSUE TITLE
[SPIKE/RESEARCH]: Async operators/sensors for AWS Glue API

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#790]
**Is your feature request related to a problem? Please describe.**
Go through the OSS operators for AWS Glue and find whether the Glue API returns a unique job id , using which an async operator/sensor can be built. The outcome of this spike would be to finalize the list of async operators/sensors which can built for Glue.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by raphaelauv** [comment]
https://github.com/apache/airflow/pull/30948

**Comment by phanikumv** [comment]
Closing as the functionality as available in OSS airflow
