### ISSUE TITLE
[SPIKE/RESEARCH]: Async operators/sensors for AWS StepFunctions API

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#791]
**Is your feature request related to a problem? Please describe.**
Go through the OSS operators for AWS StepFunctions and find whether the StepFunctions API returns a unique job id , using which an async operator/sensor can be built. 
Refer to 

- StepFunctionGetExecutionOutputOperator
- StepFunctionStartExecutionOperator
- StepFunctionExecutionSensor

The outcome of this spike would be to finalize the list of async operators/sensors which can built for AWS StepFunctions.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajastro** [comment]
We have a deferrable for `StepFunctionStartExecutionOperator` in OSS 
`StepFunctionGetExecutionOutputOperator` look like does not take much time

**Comment by phanikumv** [comment]
Closing as it is implemented in OSS
