### ISSUE TITLE
Support Multiple statements per API Call in SnowflakeOperatorAsync

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#792]
**Is your feature request related to a problem? Please describe.**

Currently, multiple SQL statements are not supported for a single API call in SnowflakeOperatorAsync because the `snowflake-connector-python` doesn't support multiple statement in a single API call.

**Describe the solution you'd like**
Based on the [issue](https://github.com/snowflakedb/snowflake-connector-python/issues/1015) ticket get closed in snowflake, give start supporting this in SnowflakeOperatorAsync

**Comment by vatsrahul1001** [comment]
@phanikumv as we are deprecating astronomer-providers, I think this is not needed now if required we can get it done in OSS as discussed with @pankajkoti.

**Comment by phanikumv** [comment]
Thats right, closing it

**Comment by phanikumv** [comment]
Thats right, closing it
