### ISSUE TITLE
ABFS support OSS Azure provider 

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#799]
https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-python

**Comment by bharanidharan14** [comment]
TODO: Create gen2 folder in Azure and check whether the hook can connect to it.

**Comment by phanikumv** [comment]
@bharanidharan14 
Please attach the OSS PR link to this ticket

**Comment by rajaths010494** [comment]
https://github.com/apache/airflow/pull/28262 has merged into OSS airflow
