### ISSUE TITLE
astronomer S3KeySensorAsync not connecting to MiniO

### ISSUE THREAD

**Issue by vsvale** [astronomer/astronomer-providers#805]
**Describe the bug**
Astronomer S3KeySensorAsync not work with same aws_conn_id used in S3KeySenson from amazon aws provider when trying to connect to with MiniO

**To Reproduce**
1. Create connection to minio:

2. In dag import from astronomer.providers.amazon.aws.sensors.s3 import S3KeySensorAsync
4. Create task, define bucket_name, bucket_key and use the created connection to minio in aws_conn_id
5. See error:
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/astronomer/providers/amazon/aws/sensors/s3.py", line 102, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

```
**Expected behavior**
When using the same connection in aws_conn_id with S3KeySensor from airflow.providers.amazon.aws.sensors.s3 a task is able to connect with Minio.

**Screenshots**
Dag
![image](https://user-images.githubusercontent.com/29167342/206573752-d24dd6ba-e5b8-4175-9fd7-52de49b8f86a.png)
Workflow
![image](https://user-images.githubusercontent.com/29167342/206575832-dfb08872-6d7e-4a3a-9953-a5d23907ca27.png)
S3KeySensor Success:
![image](https://user-images.githubusercontent.com/29167342/206573940-68eb0e68-9f60-444d-876e-ad84246daba6.png)
S3KeySensorAsync Fail:
![image](https://user-images.githubusercontent.com/29167342/206575765-c4fb2453-4449-414d-a9e5-9d8ed6731d3e.png)

**Desktop (please complete the following information):**
 - OS: Zorin OS 16.2
 - Browser Mozila Firefox for Ubuntu
 - Version 107.0 (64-bit)

**Additional context**
astronomer-providers[amazon]==1.12.0
astro-sdk-python[amazon,postgres]==1.2.3
apache/airflow:2.4.1-python3.7 with helm chart 1.7.0
kubernetes v1.24.4+k3s1

**Comment by rajaths010494** [comment]
Deleted the image since it contained access key and secret

**Comment by phanikumv** [comment]
Thank you @vsvale , we'll look into this and release a fix asap.

**Comment by bharanidharan14** [comment]
@vsvale Can you try with astronomer-providers[amazon]==1.13.0, I have tried with 1.13.0 it is working for me, because we have enhanced `AwsBaseHookAsync` in 1.13.0 release this should fix this.

**Comment by vsvale** [comment]
Thanks @bharanidharan14 with astronomer-providers[amazon]==1.13.0 the S3KeySensorAsync works like a charm.
