### ISSUE TITLE
Follow up on the usage metrics with Data team

### ISSUE THREAD

**Issue by bharanidharan14** [astronomer/astronomer-providers#806]
Need to get usage metrics of Operator/Sensor based in customer deployment, regarding this there was task Provider team has worked on to get a listener log in worker output, as next step we need to follow up with @astronaut-chris.

**Comment by bharanidharan14** [comment]
As per the Data team update on the ticket.I am reposting the plan from their end 

1st priority to be complete by 12/23 - Add async usage by looking at the` task_runs.operator` field and pulling any operator that ends with ‘async’.  This will not catch subclassed operators.

2nd priority to be complete in January - Use task listener logs to pull in additional async operator usage. Lower priority since only 6% of customers are on Astro Runtime 7

cc: @phanikumv

**Comment by rajaths010494** [comment]
https://app.zenhub.com/workspaces/airflow-providers-team-61a89ee7fbf048001dc8378d/issues/gh/astronomer/astronomer-providers/510
tracked here
