### ISSUE TITLE
Status of GKEStartPodOperatorAsync should reflect pod status.

### ISSUE THREAD

**Issue by svbatalov** [astronomer/astronomer-providers#814]
Currently `GKEStartPodOperatorAsync` (and `GKEStartPodTrigger`) succeeds whenever the pod's state is one of `PodPhase.terminal_states`, that is either `Failed` or `Succeeded`:
https://github.com/astronomer/astronomer-providers/blob/87145d157f417d674f1a6307555418935628fb44/astronomer/providers/google/cloud/triggers/kubernetes_engine.py#L120-L124

However, when underlying pod fails, it makes sense to fail `GKEStartPodOperatorAsync` as well, otherwise the DAG proceeds as if the pod succeeded.

Similarly to #811, this could be a part of #451.

**Comment by phanikumv** [comment]
Closing as https://github.com/astronomer/astronomer-providers/pull/824 is completed
