### ISSUE TITLE
Replace all OL extractors to use `DefaultExtractor`

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#821]
**Describe the bug**
Use `DefaultExtractor` for all astro provider extractors as done for astro-sdk

**Comment by phanikumv** [comment]
Can you update this ticket with the current status?

**Comment by rajaths010494** [comment]
Currently have changed redshift and snowflake.
Need to change for bigquery and add tests for the extractors.

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
