### ISSUE TITLE
Investigate SQL Pools for Synapse

### ISSUE THREAD

**Issue by virajmparekh** [astronomer/astronomer-providers#846]
Related to [this thread](https://astronomer.slack.com/archives/C0387PMM2E7/p1673872265538069), we should investigate if we can use SQL Pools on Synapse in the Synapse operators

**Comment by vatsrahul1001** [comment]
@phanikumv as per thread I think we should be good to close this?

**Comment by phanikumv** [comment]
Yes, closing it
