### ISSUE TITLE
Reorganize S3KeySensor 

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#85]
Add the trigger's common method to hooks as the methods can be reused by other sensors and triggers.

Acceptance Criteria:
- Test the example DAG 
- Unit Tests coverage in the PR (80% Code Coverage -- We will need to add CodeCov separately to measure code cov) with all of them passing
-  Example DAG using the async Operator that can be used to run Integration tests that are parametrized via Environment variables. Example - https://github.com/apache/airflow/blob/8a03a505e1df0f9de276038c5509135ac569a667/airflow/providers/google/cloud/example_dags/example_bigquery_to_gcs.py#L33-L35

**Comment by sunank200** [comment]
[PR](https://github.com/astronomer/astronomer-providers/pull/86) for the change. 

The CI is failing as coverage for snowflake and redshift cluster hooks is less than 80%.
