### ISSUE TITLE
The Hook needs to contain similar kwargs as the Google Providers

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astronomer-providers#865]
https://github.com/astronomer/astronomer-providers/blob/0cc6ba0053304582beb32c458910621046c11b36/astronomer/providers/google/cloud/operators/bigquery.py#L75

The Google Provider Hook is:

```
            self.hook = BigQueryHook(
                gcp_conn_id=self.gcp_conn_id,
                use_legacy_sql=self.use_legacy_sql,
                delegate_to=self.delegate_to,
                location=self.location,
                impersonation_chain=self.impersonation_chain,
            )
```

and the current hook for the `BigQueryInsertJobOperatorAsync` is

```
        hook = BigQueryHook(
            gcp_conn_id=self.gcp_conn_id,
            delegate_to=self.delegate_to,
            impersonation_chain=self.impersonation_chain,
        )

        self.hook = hook
```

This is causing permission issues regarding the location parameter

**Comment by pankajkoti** [comment]
This was already released in 1.15.1 https://github.com/astronomer/astronomer-providers/releases/tag/1.15.1, so removing the 1.16.0 milestone
