### ISSUE TITLE
Fix code coverage on Snowflake and Redshift Async Operators

### ISSUE THREAD

**Issue by phanikumv** [astronomer/astronomer-providers#87]
Code coverage on the Snowflake and Redshift operators is low. Lets bring it above 90%.

**Comment by phanikumv** [comment]
![image.png](https://images.zenhubusercontent.com/61a8a7dd5f00b9eb2dba7274/05a24235-4ba9-4950-acae-54363a9321b0)

**Comment by phanikumv** [comment]
@bharanidharan14 - please post the update on this ticket.

**Comment by bharanidharan14** [comment]
Fixed the test coverage Updated the PR

**Comment by bharanidharan14** [comment]
![Screenshot 2022-03-08 at 6.41.45 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/5498ba53-aa42-4736-89db-05c6677f1ddf)![Screenshot 2022-03-08 at 6.04.44 PM.png](https://images.zenhubusercontent.com/61a8a8b8234cfe4cbd2d235b/5b92a19c-dbe4-40cc-925e-e8a9d980954a)

**Comment by bharanidharan14** [comment]
Fixed

**Comment by bharanidharan14** [comment]
Created PR https://github.com/astronomer/astronomer-providers/pull/107

**Comment by phanikumv** [comment]
Closing as PR is merged to main
