### ISSUE TITLE
BigQuery.py file is out of date with current provider package

### ISSUE THREAD

**Issue by erdos2n** [astronomer/astronomer-providers#894]
**Describe the bug**
The KWARGS in the Hooks of this file need to be updated to reflect the current KWARGS of the airflow provider package. 

**Additional context**
Some of the Kwargs are in the BigQueryHook: `use_legacy_sql`, `location`

**Comment by pankajkoti** [comment]
hi @erdos2n, Can you please paste the link of the file you're mentioning for the issue? Do you have an example DAG/script which is complaining about not accepting those parameters? I also see have an example DAG accepting `location` in the operators in this DAG file https://github.com/astronomer/astronomer-providers/blob/dbbd110c230ae22a6dec0fc850ca89cb1dc84725/astronomer/providers/google/cloud/example_dags/example_bigquery_queries.py#L66

As far as I can see, in the module https://github.com/astronomer/astronomer-providers/blob/dbbd110c230ae22a6dec0fc850ca89cb1dc84725/astronomer/providers/google/cloud/hooks/bigquery.py#L25, they use the sync hook from the upstream provider, so I'm guessing it should accept all the `kwargs`

**Comment by pankajkoti** [comment]
hi @erdos2n I am closing this for now, but feel free to reopen it if you've more comments/details. 

cc: @phanikumv
