### ISSUE TITLE
Enhance test providers RC make target

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#901]
Enhance the test providers RC make target to do the following:
1. Automatically fetch the RCs to be tested from the Github URL e.g. https://github.com/apache/airflow/issues/29607
2. We miss identifying changes in the connection creations e.g. PR https://github.com/astronomer/astronomer-providers/pull/899 solves such an issue. Identify a way to re-create connections or consider creating a new deployment and deploy the image to that environment and create connections in there.

**Comment by phanikumv** [comment]
Closing as the RC make target automation has been implemented
