### ISSUE TITLE
SFTPSensorAsync not working exactly in the same way as SFTPSensor

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astronomer-providers#903]
**Describe the bug**
If a user authenticates to SFTP with login and password, `SFTPSensorAsync` throws an error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/astronomer/providers/sftp/sensors/sftp.py", line 67, in execute_complete
    raise AirflowException(event["message"])
airflow.exceptions.AirflowException: [Errno 2] No such file or directory: '"~/.ssh/known_hosts"'
```

**To Reproduce**
1. Create a local SFTP server (like shown [here](https://itnext.io/using-a-local-sftp-server-for-testing-659daaa0290a))
2. Create an Airflow connection:
  - conn id: `sftp_default`
  - conn type: `SFTP`
  - host: `host.docker.internal`
  - username: `foo`
  - password: `pass`
  - port: `2222`
3. Upload a test file to SFTP `/upload/test.txt`
4. Create a DAG:
```python
import pendulum
from airflow import DAG
from astronomer.providers.sftp.sensors.sftp import SFTPSensorAsync

with DAG(
    dag_id="sftp_test",
    start_date=pendulum.datetime(2023, 2, 1, tz="UTC"),
    schedule="@once",
):

    wait_for_file = SFTPSensorAsync(
        task_id="wait_for_file",
        sftp_conn_id="sftp_default",
        path="/upload/test.txt",
        poke_interval=15,
        timeout=60 * 10,
    )
```
5. See error
![image](https://user-images.githubusercontent.com/97064715/221833447-22728ad8-d21a-4d44-ba22-ea7f447ef0eb.png)

**Expected behavior**
`SFTPSensorAsync` should work in the same way as `SFTPSensor`. Now it only works after adding `{"known_hosts": "none"}` to the `Extra` field.

**Comment by rajaths010494** [comment]
Currently, default value for known_hosts has been set to `"~/.ssh/known_hosts"` instead of which user explicitly sends known_hosts from the connection consider it or else consider the default value to be `None`
