### ISSUE TITLE
SFTPSensorAsync to start supporting host key

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astronomer-providers#906]
**Is your feature request related to a problem? Please describe.**
`SFTPSensorAsync` currently does not support host keys (whereas `SFTPSensor` does) which prevent against man in the middle attacks.

**Describe the solution you'd like**
I would like the same support for all types of authorization like in the traditional operator.

**Comment by pankajkoti** [comment]
I reached out to @magdagultekin and @rajaths010494 earlier today to understand the issue more. Looks like Magda created this issue post a discussion with Rajath during a customer interaction. We do not have an example DAG showing exactly what works with the Sync version and what does not work with Async version. 

I started understanding more about host keys wrt SFTP. Currently, I am trying to use the Sync sensor using host key of an EC2 instance which I got by turning on an instance and running `ssh-keyscan <ec2-public-ip>`. However, setting the got host keys in the sftp connection do not seem to help as of now and the DAG is failing. I am continuing to get the DAG working by trying various combinations of the host keys. Will update here more if I could progress further.
