### ISSUE TITLE
KubernetesPodOperatorAsync not using AIRFLOW__KUBERNETES__CONFIG_FILE

### ISSUE THREAD

**Issue by raphaelauv** [astronomer/astronomer-providers#94]
**Describe the bug**

the env variable AIRFLOW__KUBERNETES__CONFIG_FILE is not used by the KubernetesPodOperatorAsync

**To Reproduce**

set 
AIRFLOW__KUBERNETES__CONFIG_FILE=/usr/local/airflow/include/.kube/config

then it will log 
Config not found: ~/.kube/config

**Comment by kaxil** [comment]
@raphaelauv Where did you see this log, on `Triggerer` or `Scheduler` ?

**Comment by raphaelauv** [comment]
in the Triggerer

```log
[2022-03-11 10:41:14,176] {triggerer_job.py:356} INFO - Trigger <astronomer.providers.cncf.kubernetes.triggers.wait_container.WaitContainerTrigger kubernetes_conn_id=None, hook_params={'cluster_context': None, 'config_file': None, 'in_cluster': None}, pod_name=airflow-test-pod.3279ee5034e046e2baa4b22d746cabf4, container_name=base, pod_namespace=default, pending_phase_timeout=120, poll_interval=10> (ID 9) starting
2022-03-11T10:41:14.186014105Z [2022-03-11 10:41:14,176] {kube_config.py:482} WARNING - Config not found: ~/.kube/config
```

**Comment by kaxil** [comment]
Looks like we have the same thing with `KubernetesPodOperator`, currently that setting is mostly for `KubernetesExecutor` and we can make it explicit in Airflow docs or start using the configs for KPO too :) 

The other thing you could do is:

```python
    KubernetesPodOperatorAsync(
        config_file=conf.get("kubernetes", "config_file"),
        namespace=conf.get("kubernetes", "namespace"),
        ...
```

That way, it will work for all different ways of settings Airflow configs: Secrets Backend, Env Vars, airflow.cfg :)

**Comment by raphaelauv** [comment]
No AIRFLOW__KUBERNETES__CONFIG_FILE work with the KubernetesPodOperator because of this line 

https://github.com/apache/airflow/blob/3452f7ce45607af04bade5e5edebaa18fdc13819/airflow/kubernetes/kube_client.py#L133

call by https://github.com/apache/airflow/blob/3452f7ce45607af04bade5e5edebaa18fdc13819/airflow/providers/cncf/kubernetes/operators/kubernetes_pod.py#L320

**Comment by kaxil** [comment]
Oh yes, you are absolutely right, we will fix it and release a new version soon :)

**Comment by dstandish** [comment]
actually i would prefer if we do not add support for using the config.  as @raphaelauv has pointed out, users can set the config file in operator param.  and once we add support for k8s hook in kpo, then users can just set it in k8s connection.

if we add support for taking values from conf, then we'll have to make a major release in astro operators to remove it.  it seems that if we document this difference, then when switching to this operator they can also take care to set param.  

what do yall think?

**Comment by raphaelauv** [comment]
I agree with you, using a K8S connection will be nicer, so let's not add this feature to the KPOA.

**Comment by kaxil** [comment]
Yup agreed, thank you both
