### ISSUE TITLE
combine Redshift cluster management, sql and data DAG

### ISSUE THREAD

**Issue by pankajastro** [astronomer/astronomer-providers#942]
currently, we have 3 DAG and 3 times we create and delete cluster. Find the possibility to combine it
- https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/amazon/aws/example_dags/example_redshift_cluster_management.py
- https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/amazon/aws/example_dags/example_redshift_data.py
- https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/amazon/aws/example_dags/example_redshift_sql.py

**Comment by vatsrahul1001** [comment]
As we are deprecating Astronomer Providers, we might not need this anymore, closing this
