### ISSUE TITLE
GCS custom xcom backend does not work with pandas Dataframes (expects str got bytes)

### ISSUE THREAD

**Issue by jherrmannNetfonds** [astronomer/astronomer-providers#955]
**Describe the bug**
When using astronomer-providers gcs xcom backend, loading pandas Dataframes fails. Because in [gcs.py Line 94](https://github.com/astronomer/astronomer-providers/blob/main/astronomer/providers/google/cloud/xcom_backends/gcs.py#L94)  we expect a string, but GCSHook returns `bytes`. See [hook implementation](https://github.com/apache/airflow/blob/main/airflow/providers/google/cloud/hooks/gcs.py#L311). 

**To Reproduce**
1. Have airflow configured to use astronomer-providers gcs xcom backend
2. Create a DAG with two Tasks
a. Creating and return a pandas DF
b. Loading the created DF from xcom
3. See error in logs

**Expected behavior**
Passing Dataframes via xcom should work

**Additional context**
To fix the issue we have to decide if the data should be saved as file or if we convert the byte array. I could create a PR if we get some opinions on a possible solution.

**Comment by pankajkoti** [comment]
Thanks for trying out the xcom backend and reporting the issue @jherrmannNetfonds. I agree with the pandas read_json, if the instance is bytes, I believe we could convert it to BytesIO. Introducing something like the below just before read_json() on line 94 should work I believe:
```
if isinstance(data, bytes):
    data = BytesIO(data)
```

where BytesIO is imported from io
`from io import BytesIO`

**Comment by pankajkoti** [comment]
Hi, @jherrmannNetfonds looks like we have a similar issue in the S3 Custom XCOM backend and we will need to address this on priority as other users might face the issue too. I have opened a PR for the fix now, however, looking forward to collaborating with you soon on other issues.
