### ISSUE TITLE
Incompatibility with Airflow 2.2.4

### ISSUE THREAD

**Issue by fj-sanchez** [astronomer/astronomer-providers#96]
**Describe the bug**
If you try to install `airflow==2.2.4` with the `astronomer-providers==1.0.0` it will run into a dependency version conflict.

**To Reproduce**
1. Create a fresh virtualenv with Python 3.9: `pyenv virtualenv 3.9.7 airflow-test`
2. Activate the virtualenv: `pyenv virtualenv activate airlfow-test`
3. Install Airflow 2.2.4 with S3 extras and astronomer-provider 1.0.0: `pip install "apache-airflow[s3]==2.2.4" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.9.txt" "astronomer-providers==1.0.0"`
4. You get an error halfway through:
```
ERROR: Cannot install astronomer-providers because these package versions have conflicting dependencies.

The conflict is caused by:
    aiobotocore 2.1.1 depends on botocore<1.23.25 and >=1.23.24
    The user requested (constraint) botocore==1.24.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

**Expected behavior**
It should install cleanly.

**Additional context**
[Airflow 2.2.4 constraints](https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.9.txt): `botocore==1.24.2`
[astronomer-providers 1.0.0 requirements](https://github.com/astronomer/astronomer-providers/blob/1.0.0/setup.cfg#L48): `aiobotocore>=2.1.1`
[aiobotocore 2.1.1 requirements](https://github.com/aio-libs/aiobotocore/blob/2.1.1/setup.py#L10): `botocore>=1.23.24,<1.23.25`

There might be similar issues with the other boto dependencies... I have tried with 2.2.3 and 2.2.2 but there are similar issues with a different packages:
e.g. 2.2.3:
```
The conflict is caused by:
    astronomer-providers 1.0.0 depends on apache-airflow-providers-cncf-kubernetes>=3
    The user requested (constraint) apache-airflow-providers-cncf-kubernetes==2.2.0
```

e.g. 2.2.2:
```
The conflict is caused by:
    apache-airflow[s3] 2.2.2 depends on apache-airflow-providers-amazon; extra == "s3"
    astronomer-providers 1.0.0 depends on apache-airflow-providers-amazon>=3.0.0
    The user requested (constraint) apache-airflow-providers-amazon==2.4.0
```

**Comment by kaxil** [comment]
Thanks for raising the issue @fj-sanchez  . This is a known issue, I have created a GitHub issue on aio-botocore [here](https://github.com/aio-libs/aiobotocore/issues/924). 

For now, you can install it as follows:

```
pip install "apache-airflow[s3]==2.2.4" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.2.4/constraints-3.9.txt"
pip install "astronomer-providers==1.0.0"
```

OR

```
pip install "apache-airflow[s3]==2.2.4" --constraint https://github.com/apache/airflow/blob/constraints-2.2.4/constraints-no-providers-3.9.txt pip install "astronomer-providers==1.0.0"
```

We publish constraints in Airflow, mainly to have a set of "known-working" dependencies but in this case that is causing conflict with `aiobotocore`. This will happen from time to time, however as long as the dependencies from `astronomer-providers` don't conflict with the ones in Airflow repo (mentioned in `setup.py` or `setup.cfg`) we are fine. As long as we remain compatible to [Constraints without providers](https://github.com/apache/airflow/blob/constraints-2.2.4/constraints-no-providers-3.9.txt) we are good. Astronomer Providers repo will also publish it's own set of constraints fine from 1.1.0 onwards
