### ISSUE TITLE
Extend CI to run tests on multilple version of providers

### ISSUE THREAD

**Issue by utkarsharma2** [astronomer/astronomer-providers#975]
**Is your feature request related to a problem? Please describe.**
Currently, we are not running tests on all the versions of providers we support. 

**Describe the solution you'd like**
We should extend CI to run them on all/most of the versions we support.

**Additional context**
Recently there was a P0 issue that we could have avoided if we had tested for an old version of the provider. 
ref - https://github.com/astronomer/astronomer-providers/issues/966

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
