### ISSUE TITLE
Test Airflow Providers prepared on April 21, 2023

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astronomer-providers#977]
Test the following RCs

1. https://pypi.org/project/apache-airflow-providers-amazon/8.0.0rc1/
2. https://pypi.org/project/apache-airflow-providers-cncf-kubernetes/6.1.0rc1/
3. https://pypi.org/project/apache-airflow-providers-databricks/4.1.0rc1/
4. https://pypi.org/project/apache-airflow-providers-dbt-cloud/3.1.1rc1/
5. https://pypi.org/project/apache-airflow-providers-google/10.0.0rc1/
6. https://pypi.org/project/apache-airflow-providers-microsoft-azure/6.0.0rc1/
7. https://pypi.org/project/apache-airflow-providers-snowflake/4.0.5rc1/

Test that mypy checks, unit tests and example DAGs run fine and make necessary implementation changes to make the operators/sensors future ready for the providers release and ensuring backward compatibility for the older versions.

**Comment by pankajastro** [comment]
@pankajkoti can we close this?

**Comment by pankajkoti** [comment]
yes, thanks for the check @pankajastro, the corresponding PR was marked closed and we have tested the RCs. Closing it now.
