### ISSUE TITLE
[GitHub Actions] support layer cache in workflow deploy-integration-tests-to-astro-cloud 

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#997]
**Is your feature request related to a problem? Please describe.**
The auto deployment process can use layer cache to save some building time.

**Describe the solution you'd like**
Use [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) and [docker/build-push-action](https://github.com/docker/build-push-action) and the cache feature in [docker/build-push-action](https://github.com/docker/build-push-action)

**Describe alternatives you've considered**

**Additional context**
[How to use Docker layer caching in GitHub Actions](https://depot.dev/blog/docker-layer-caching-in-github-actions)

We need to make sure `RUN pip install  --upgrade --force-reinstall  --no-cache-dir /tmp/astronomer-providers[all]` is not cached and updated every time.

**Comment by vatsrahul1001** [comment]
As we are deprecating providers, this might not be needed now. closing this
