### ISSUE TITLE
Check the deploying results when deploying integration tests

### ISSUE THREAD

**Issue by Lee-W** [astronomer/astronomer-providers#998]
**Is your feature request related to a problem? Please describe.**
As [job 8553905019](https://github.com/astronomer/astronomer-providers/actions/runs/4806413225/jobs/8553905019#step:3:13504) indicates, we did not check the deployment result but only check whether the deploying command succeeded which gives us a false positive result

**Describe the solution you'd like**
Check whether the results of [deploying command](https://github.com/astronomer/astronomer-providers/blob/main/.circleci/integration-tests/script.sh#L109) returns error

**Describe alternatives you've considered**

**Additional context**

**Comment by vatsrahul1001** [comment]
Already done. Closing this
